In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('Amazon Web Services.csv')

In [3]:
data

                    user_name#repo_name#star#repo_url
0   serverless#serverless#39700#https://github.com...
1   localstack#localstack#30300#https://github.com...
2   donnemartin#data-science-ipython-notebooks#211...
3   ramitsurana#awesome-kubernetes#11600#https://g...
4   aws#aws-cli#11000#https://github.com//aws/aws-cli
5   kubernetes-sigs#kubespray#10600#https://github...
6   donnemartin#awesome-aws#9300#https://github.co...
7      apereo#cas#8600#https://github.com//apereo/cas
8   pulumi#pulumi#8600#https://github.com//pulumi/...
9   bregman-arie#devops-exercises#8400#https://git...
10           apex#up#8200#https://github.com//apex/up
11  aws-amplify#amplify-js#8100#https://github.com...
12   aws#chalice#7900#https://github.com//aws/chalice
13  aws#serverless-application-model#7900#https://...
14  google#go-cloud#7700#https://github.com//googl...
15  mozilla#sops#7500#https://github.com//mozilla/...
16  caprover#caprover#7100#https://github.com//cap...
17  aws#aws-sdk-go#6900#https://github.com//aws/aw...
18   aws#aws-cdk#6700#https://github.com//aws/aws-cdk
19  aws#aws-sdk-js#6600#https://github.com//aws/aw...
20     boto#boto3#6400#https://github.com//boto/boto3
21  angristan#openvpn-install#6300#https://github....
22  awslabs#aws-shell#6100#https://github.com//aws...
23  hashicorp#terraform-provider-aws#5800#https://...
24  aws#aws-sam-cli#5500#https://github.com//aws/a...
25  aws#amazon-sagemaker-examples#5500#https://git...
26  donnemartin#dev-setup#5400#https://github.com/...
27  gruntwork-io#terratest#5200#https://github.com...
28  gruntwork-io#terragrunt#5000#https://github.co...
29  99designs#aws-vault#4900#https://github.com//9...

In [4]:
data.head()

                   user_name#repo_name#star#repo_url
0  serverless#serverless#39700#https://github.com...
1  localstack#localstack#30300#https://github.com...
2  donnemartin#data-science-ipython-notebooks#211...
3  ramitsurana#awesome-kubernetes#11600#https://g...
4  aws#aws-cli#11000#https://github.com//aws/aws-cli

In [5]:
data.head(20)

                    user_name#repo_name#star#repo_url
0   serverless#serverless#39700#https://github.com...
1   localstack#localstack#30300#https://github.com...
2   donnemartin#data-science-ipython-notebooks#211...
3   ramitsurana#awesome-kubernetes#11600#https://g...
4   aws#aws-cli#11000#https://github.com//aws/aws-cli
5   kubernetes-sigs#kubespray#10600#https://github...
6   donnemartin#awesome-aws#9300#https://github.co...
7      apereo#cas#8600#https://github.com//apereo/cas
8   pulumi#pulumi#8600#https://github.com//pulumi/...
9   bregman-arie#devops-exercises#8400#https://git...
10           apex#up#8200#https://github.com//apex/up
11  aws-amplify#amplify-js#8100#https://github.com...
12   aws#chalice#7900#https://github.com//aws/chalice
13  aws#serverless-application-model#7900#https://...
14  google#go-cloud#7700#https://github.com//googl...
15  mozilla#sops#7500#https://github.com//mozilla/...
16  caprover#caprover#7100#https://github.com//cap...
17  aws#aws-sdk-go#6900#https://github.com//aws/aw...
18   aws#aws-cdk#6700#https://github.com//aws/aws-cdk
19  aws#aws-sdk-js#6600#https://github.com//aws/aw...

In [6]:
data.tail()

                    user_name#repo_name#star#repo_url
25  aws#amazon-sagemaker-examples#5500#https://git...
26  donnemartin#dev-setup#5400#https://github.com/...
27  gruntwork-io#terratest#5200#https://github.com...
28  gruntwork-io#terragrunt#5000#https://github.co...
29  99designs#aws-vault#4900#https://github.com//9...

In [7]:
type(data)

pandas.core.frame.DataFrame

In [8]:
df= data.head()

In [9]:
df.to_csv('my_csv.csv')

In [10]:
pwd()

'D:\\Data_science_class\\pandas'

In [11]:
!dir

 Volume in drive D is New Volume
 Volume Serial Number is 1EDA-CC31

 Directory of D:\Data_science_class\pandas

10-06-2021  06:44    <DIR>          .
10-06-2021  06:44    <DIR>          ..
06-06-2021  16:08    <DIR>          .ipynb_checkpoints
06-06-2021  10:18             2,067 Amazon Web Services.csv
06-06-2021  15:42        43,890,380 cricket_data.csv
10-06-2021  06:51               441 my_csv.csv
06-06-2021  15:23             3,076 my_picle
10-06-2021  06:44           205,444 pandas.ipynb
06-06-2021  16:00            32,627 Player.csv
10-06-2021  06:50             7,116 result.csv
               7 File(s)     44,141,151 bytes
               3 Dir(s)  57,835,048,960 bytes free

In [12]:
pd.read_csv('my_csv.csv')

   Unnamed: 0                  user_name#repo_name#star#repo_url
0           0  serverless#serverless#39700#https://github.com...
1           1  localstack#localstack#30300#https://github.com...
2           2  donnemartin#data-science-ipython-notebooks#211...
3           3  ramitsurana#awesome-kubernetes#11600#https://g...
4           4  aws#aws-cli#11000#https://github.com//aws/aws-cli

In [13]:
pd.read_csv('Amazon Web Services.csv')

                    user_name#repo_name#star#repo_url
0   serverless#serverless#39700#https://github.com...
1   localstack#localstack#30300#https://github.com...
2   donnemartin#data-science-ipython-notebooks#211...
3   ramitsurana#awesome-kubernetes#11600#https://g...
4   aws#aws-cli#11000#https://github.com//aws/aws-cli
5   kubernetes-sigs#kubespray#10600#https://github...
6   donnemartin#awesome-aws#9300#https://github.co...
7      apereo#cas#8600#https://github.com//apereo/cas
8   pulumi#pulumi#8600#https://github.com//pulumi/...
9   bregman-arie#devops-exercises#8400#https://git...
10           apex#up#8200#https://github.com//apex/up
11  aws-amplify#amplify-js#8100#https://github.com...
12   aws#chalice#7900#https://github.com//aws/chalice
13  aws#serverless-application-model#7900#https://...
14  google#go-cloud#7700#https://github.com//googl...
15  mozilla#sops#7500#https://github.com//mozilla/...
16  caprover#caprover#7100#https://github.com//cap...
17  aws#aws-sdk-go#6900#https://github.com//aws/aw...
18   aws#aws-cdk#6700#https://github.com//aws/aws-cdk
19  aws#aws-sdk-js#6600#https://github.com//aws/aw...
20     boto#boto3#6400#https://github.com//boto/boto3
21  angristan#openvpn-install#6300#https://github....
22  awslabs#aws-shell#6100#https://github.com//aws...
23  hashicorp#terraform-provider-aws#5800#https://...
24  aws#aws-sam-cli#5500#https://github.com//aws/a...
25  aws#amazon-sagemaker-examples#5500#https://git...
26  donnemartin#dev-setup#5400#https://github.com/...
27  gruntwork-io#terratest#5200#https://github.com...
28  gruntwork-io#terragrunt#5000#https://github.co...
29  99designs#aws-vault#4900#https://github.com//9...

In [14]:
pd.read_csv('Amazon Web Services.csv', sep='#')

,user_name,repo_name,star,repo_url
0,serverless,serverless,39700,https://github.com//serverless/serverless
1,localstack,localstack,30300,https://github.com//localstack/localstack
2,donnemartin,data-science-ipython-notebooks,21100,https://github.com//donnemartin/data-science-i...
3,ramitsurana,awesome-kubernetes,11600,https://github.com//ramitsurana/awesome-kubern...
4,aws,aws-cli,11000,https://github.com//aws/aws-cli
5,kubernetes-sigs,kubespray,10600,https://github.com//kubernetes-sigs/kubespray
6,donnemartin,awesome-aws,9300,https://github.com//donnemartin/awesome-aws
7,apereo,cas,8600,https://github.com//apereo/cas
8,pulumi,pulumi,8600,https://github.com//pulumi/pulumi
9,bregman-arie,devops-exercises,8400,https://github.com//bregman-arie/devops-exercises
10,apex,up,8200,https://github.com//apex/up
11,aws-amplify,amplify-js,8100,https://github.com//aws-amplify/amplify-js
12,aws,chalice,7900,https://github.com//aws/chalice
13,aws,serverless-application-model,7900,https://github.com//aws/serverless-application...
14,google,go-cloud,7700,https://github.com//google/go-cloud
15,mozilla,sops,7500,https://github.com//mozilla/sops
16,caprover,caprover,7100,https://github.com//caprover/caprover
17,aws,aws-sdk-go,6900,https://github.com//aws/aws-sdk-go
18,aws,aws-cdk,6700,https://github.com//aws/aws-cdk
19,aws,aws-sdk-js,6600,https://github.com//aws/aws-sdk-js
20,boto,boto3,6400,https://github.com//boto/boto3
21,angristan,openvpn-install,6300,https://github.com//angristan/openvpn-install
22,awslabs,aws-shell,6100,https://github.com//awslabs/aws-shell
23,hashicorp,terraform-provider-aws,5800,https://github.com//hashicorp/terraform-provid...
24,aws,aws-sam-cli,5500,https://github.com//aws/aws-sam-cli
25,aws,amazon-sagemaker-examples,5500,https://github.com//aws/amazon-sagemaker-examples
26,donnemartin,dev-setup,5400,https://github.com//donnemartin/dev-setup
27,gruntwork-io,terratest,5200,https://github.com//gruntwork-io/terratest
28,gruntwork-io,terragrunt,5000,https://github.com//gruntwork-io/terragrunt
29,99designs,aws-vault,4900,https://github.com//99designs/aws-vault

In [15]:
pd.read_csv('Amazon Web Services.csv', sep='#', header=None)

,0,1,2,3
0,user_name,repo_name,star,repo_url
1,serverless,serverless,39700,https://github.com//serverless/serverless
2,localstack,localstack,30300,https://github.com//localstack/localstack
3,donnemartin,data-science-ipython-notebooks,21100,https://github.com//donnemartin/data-science-i...
4,ramitsurana,awesome-kubernetes,11600,https://github.com//ramitsurana/awesome-kubern...
5,aws,aws-cli,11000,https://github.com//aws/aws-cli
6,kubernetes-sigs,kubespray,10600,https://github.com//kubernetes-sigs/kubespray
7,donnemartin,awesome-aws,9300,https://github.com//donnemartin/awesome-aws
8,apereo,cas,8600,https://github.com//apereo/cas
9,pulumi,pulumi,8600,https://github.com//pulumi/pulumi
10,bregman-arie,devops-exercises,8400,https://github.com//bregman-arie/devops-exercises
11,apex,up,8200,https://github.com//apex/up
12,aws-amplify,amplify-js,8100,https://github.com//aws-amplify/amplify-js
13,aws,chalice,7900,https://github.com//aws/chalice
14,aws,serverless-application-model,7900,https://github.com//aws/serverless-application...
15,google,go-cloud,7700,https://github.com//google/go-cloud
16,mozilla,sops,7500,https://github.com//mozilla/sops
17,caprover,caprover,7100,https://github.com//caprover/caprover
18,aws,aws-sdk-go,6900,https://github.com//aws/aws-sdk-go
19,aws,aws-cdk,6700,https://github.com//aws/aws-cdk
20,aws,aws-sdk-js,6600,https://github.com//aws/aws-sdk-js
21,boto,boto3,6400,https://github.com//boto/boto3
22,angristan,openvpn-install,6300,https://github.com//angristan/openvpn-install
23,awslabs,aws-shell,6100,https://github.com//awslabs/aws-shell
24,hashicorp,terraform-provider-aws,5800,https://github.com//hashicorp/terraform-provid...
25,aws,aws-sam-cli,5500,https://github.com//aws/aws-sam-cli
26,aws,amazon-sagemaker-examples,5500,https://github.com//aws/amazon-sagemaker-examples
27,donnemartin,dev-setup,5400,https://github.com//donnemartin/dev-setup
28,gruntwork-io,terratest,5200,https://github.com//gruntwork-io/terratest
29,gruntwork-io,terragrunt,5000,https://github.com//gruntwork-io/terragrunt
30,99designs,aws-vault,4900,https://github.com//99designs/aws-vault

In [16]:
#change the name of collumn 
pd.read_csv('Amazon Web Services.csv', sep='#', header=None, names=['a','b','c','d','e'])

,a,b,c,d,e
0,user_name,repo_name,star,repo_url,NaN
1,serverless,serverless,39700,https://github.com//serverless/serverless,NaN
2,localstack,localstack,30300,https://github.com//localstack/localstack,NaN
3,donnemartin,data-science-ipython-notebooks,21100,https://github.com//donnemartin/data-science-i...,NaN
4,ramitsurana,awesome-kubernetes,11600,https://github.com//ramitsurana/awesome-kubern...,NaN
5,aws,aws-cli,11000,https://github.com//aws/aws-cli,NaN
6,kubernetes-sigs,kubespray,10600,https://github.com//kubernetes-sigs/kubespray,NaN
7,donnemartin,awesome-aws,9300,https://github.com//donnemartin/awesome-aws,NaN
8,apereo,cas,8600,https://github.com//apereo/cas,NaN
9,pulumi,pulumi,8600,https://github.com//pulumi/pulumi,NaN
10,bregman-arie,devops-exercises,8400,https://github.com//bregman-arie/devops-exercises,NaN
11,apex,up,8200,https://github.com//apex/up,NaN
12,aws-amplify,amplify-js,8100,https://github.com//aws-amplify/amplify-js,NaN
13,aws,chalice,7900,https://github.com//aws/chalice,NaN
14,aws,serverless-application-model,7900,https://github.com//aws/serverless-application...,NaN
15,google,go-cloud,7700,https://github.com//google/go-cloud,NaN
16,mozilla,sops,7500,https://github.com//mozilla/sops,NaN
17,caprover,caprover,7100,https://github.com//caprover/caprover,NaN
18,aws,aws-sdk-go,6900,https://github.com//aws/aws-sdk-go,NaN
19,aws,aws-cdk,6700,https://github.com//aws/aws-cdk,NaN
20,aws,aws-sdk-js,6600,https://github.com//aws/aws-sdk-js,NaN
21,boto,boto3,6400,https://github.com//boto/boto3,NaN
22,angristan,openvpn-install,6300,https://github.com//angristan/openvpn-install,NaN
23,awslabs,aws-shell,6100,https://github.com//awslabs/aws-shell,NaN
24,hashicorp,terraform-provider-aws,5800,https://github.com//hashicorp/terraform-provid...,NaN
25,aws,aws-sam-cli,5500,https://github.com//aws/aws-sam-cli,NaN
26,aws,amazon-sagemaker-examples,5500,https://github.com//aws/amazon-sagemaker-examples,NaN
27,donnemartin,dev-setup,5400,https://github.com//donnemartin/dev-setup,NaN
28,gruntwork-io,terratest,5200,https://github.com//gruntwork-io/terratest,NaN
29,gruntwork-io,terragrunt,5000,https://github.com//gruntwork-io/terragrunt,NaN
30,99designs,aws-vault,4900,https://github.com//99designs/aws-vault,NaN

In [17]:
pd.read_csv('Amazon Web Services.csv', sep='#', header=None, names=['a','b','c','d','e'], skiprows=[0,4,6])

,a,b,c,d,e
0,serverless,serverless,39700,https://github.com//serverless/serverless,NaN
1,localstack,localstack,30300,https://github.com//localstack/localstack,NaN
2,donnemartin,data-science-ipython-notebooks,21100,https://github.com//donnemartin/data-science-i...,NaN
3,aws,aws-cli,11000,https://github.com//aws/aws-cli,NaN
4,donnemartin,awesome-aws,9300,https://github.com//donnemartin/awesome-aws,NaN
5,apereo,cas,8600,https://github.com//apereo/cas,NaN
6,pulumi,pulumi,8600,https://github.com//pulumi/pulumi,NaN
7,bregman-arie,devops-exercises,8400,https://github.com//bregman-arie/devops-exercises,NaN
8,apex,up,8200,https://github.com//apex/up,NaN
9,aws-amplify,amplify-js,8100,https://github.com//aws-amplify/amplify-js,NaN
10,aws,chalice,7900,https://github.com//aws/chalice,NaN
11,aws,serverless-application-model,7900,https://github.com//aws/serverless-application...,NaN
12,google,go-cloud,7700,https://github.com//google/go-cloud,NaN
13,mozilla,sops,7500,https://github.com//mozilla/sops,NaN
14,caprover,caprover,7100,https://github.com//caprover/caprover,NaN
15,aws,aws-sdk-go,6900,https://github.com//aws/aws-sdk-go,NaN
16,aws,aws-cdk,6700,https://github.com//aws/aws-cdk,NaN
17,aws,aws-sdk-js,6600,https://github.com//aws/aws-sdk-js,NaN
18,boto,boto3,6400,https://github.com//boto/boto3,NaN
19,angristan,openvpn-install,6300,https://github.com//angristan/openvpn-install,NaN
20,awslabs,aws-shell,6100,https://github.com//awslabs/aws-shell,NaN
21,hashicorp,terraform-provider-aws,5800,https://github.com//hashicorp/terraform-provid...,NaN
22,aws,aws-sam-cli,5500,https://github.com//aws/aws-sam-cli,NaN
23,aws,amazon-sagemaker-examples,5500,https://github.com//aws/amazon-sagemaker-examples,NaN
24,donnemartin,dev-setup,5400,https://github.com//donnemartin/dev-setup,NaN
25,gruntwork-io,terratest,5200,https://github.com//gruntwork-io/terratest,NaN
26,gruntwork-io,terragrunt,5000,https://github.com//gruntwork-io/terragrunt,NaN
27,99designs,aws-vault,4900,https://github.com//99designs/aws-vault,NaN

In [18]:
import pandas as pd

In [19]:
pd.read_csv('Player.csv', na_values=[1])

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,NaN,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0.0,NaN
1,2.0,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0.0,NaN
2,3.0,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0.0,NaN
3,4.0,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0.0,NaN
4,5.0,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0.0,NaN
...,...,...,...,...,...,...,...,...
518,519.0,Subroto Das,NaN,NaN,NaN,India,NaN,NaN
519,520.0,K Srinivasan,NaN,NaN,NaN,India,NaN,NaN
520,521.0,VK Sharma,NaN,NaN,NaN,India,NaN,NaN
521,523.0,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0.0,NaN
522,524.0,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0.0,NaN

In [20]:
pd.read_csv('Player.csv', na_values=['SC Ganguly'])

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,NaN,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [21]:
pd.read_csv('Player.csv', na_values=['SC Ganguly', 'BB McCullum'])

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,NaN,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,NaN,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
...,...,...,...,...,...,...,...,...
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [22]:
pd.read_csv('Amazon Web Services.csv', sep='#', na_values=['serverless'])

,user_name,repo_name,star,repo_url
0,NaN,NaN,39700,https://github.com//serverless/serverless
1,localstack,localstack,30300,https://github.com//localstack/localstack
2,donnemartin,data-science-ipython-notebooks,21100,https://github.com//donnemartin/data-science-i...
3,ramitsurana,awesome-kubernetes,11600,https://github.com//ramitsurana/awesome-kubern...
4,aws,aws-cli,11000,https://github.com//aws/aws-cli
5,kubernetes-sigs,kubespray,10600,https://github.com//kubernetes-sigs/kubespray
6,donnemartin,awesome-aws,9300,https://github.com//donnemartin/awesome-aws
7,apereo,cas,8600,https://github.com//apereo/cas
8,pulumi,pulumi,8600,https://github.com//pulumi/pulumi
9,bregman-arie,devops-exercises,8400,https://github.com//bregman-arie/devops-exercises
10,apex,up,8200,https://github.com//apex/up
11,aws-amplify,amplify-js,8100,https://github.com//aws-amplify/amplify-js
12,aws,chalice,7900,https://github.com//aws/chalice
13,aws,serverless-application-model,7900,https://github.com//aws/serverless-application...
14,google,go-cloud,7700,https://github.com//google/go-cloud
15,mozilla,sops,7500,https://github.com//mozilla/sops
16,caprover,caprover,7100,https://github.com//caprover/caprover
17,aws,aws-sdk-go,6900,https://github.com//aws/aws-sdk-go
18,aws,aws-cdk,6700,https://github.com//aws/aws-cdk
19,aws,aws-sdk-js,6600,https://github.com//aws/aws-sdk-js
20,boto,boto3,6400,https://github.com//boto/boto3
21,angristan,openvpn-install,6300,https://github.com//angristan/openvpn-install
22,awslabs,aws-shell,6100,https://github.com//awslabs/aws-shell
23,hashicorp,terraform-provider-aws,5800,https://github.com//hashicorp/terraform-provid...
24,aws,aws-sam-cli,5500,https://github.com//aws/aws-sam-cli
25,aws,amazon-sagemaker-examples,5500,https://github.com//aws/amazon-sagemaker-examples
26,donnemartin,dev-setup,5400,https://github.com//donnemartin/dev-setup
27,gruntwork-io,terratest,5200,https://github.com//gruntwork-io/terratest
28,gruntwork-io,terragrunt,5000,https://github.com//gruntwork-io/terragrunt
29,99designs,aws-vault,4900,https://github.com//99designs/aws-vault

In [23]:
pd.read_csv('Player.csv', skiprows=[0,1,4])

,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,Unnamed: 7
0,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
1,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN
2,6,R Dravid,11-Jan-73,Right_Hand,Right-arm offbreak,India,0,NaN
3,7,W Jaffer,16-Feb-78,Right_Hand,Right-arm offbreak,India,0,NaN
4,8,V Kohli,5-Nov-88,Right_Hand,Right-arm medium,India,0,NaN
...,...,...,...,...,...,...,...,...
515,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
516,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
517,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
518,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
519,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [24]:
data.describe()

                        user_name#repo_name#star#repo_url
count                                                  30
unique                                                 30
top     aws#aws-sam-cli#5500#https://github.com//aws/a...
freq                                                    1

In [25]:
data.dtypes

user_name#repo_name#star#repo_url    object
dtype: object

In [26]:
df=pd.read_csv('Player.csv')

In [27]:
df.dtypes

Player_Id          int64
Player_Name       object
DOB               object
Batting_Hand      object
Bowling_Skill     object
Country           object
Is_Umpire          int64
Unnamed: 7       float64
dtype: object

In [28]:
#by defualt description gives the only numerical data description
df.describe()

        Player_Id   Is_Umpire  Unnamed: 7
count  523.000000  523.000000   12.000000
mean   262.003824    0.099426    6.500000
std    151.127981    0.299520    3.605551
min      1.000000    0.000000    1.000000
25%    131.500000    0.000000    3.750000
50%    262.000000    0.000000    6.500000
75%    392.500000    0.000000    9.250000
max    524.000000    1.000000   12.000000

In [29]:
df.head()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
0,1,SC Ganguly,8-Jul-72,Left_Hand,Right-arm medium,India,0,NaN
1,2,BB McCullum,27-Sep-81,Right_Hand,Right-arm medium,New Zealand,0,NaN
2,3,RT Ponting,19-Dec-74,Right_Hand,Right-arm medium,Australia,0,NaN
3,4,DJ Hussey,15-Jul-77,Right_Hand,Right-arm offbreak,Australia,0,NaN
4,5,Mohammad Hafeez,17-Oct-80,Right_Hand,Right-arm offbreak,Pakistan,0,NaN

In [30]:
df.to_csv('result.csv', index=False, header=False, columns=['Player_Id', 'DOB'])

In [31]:
df.tail()

,Player_Id,Player_Name,DOB,Batting_Hand,Bowling_Skill,Country,Is_Umpire,Unnamed: 7
518,519,Subroto Das,NaN,NaN,NaN,India,1,NaN
519,520,K Srinivasan,NaN,NaN,NaN,India,1,NaN
520,521,VK Sharma,NaN,NaN,NaN,India,1,NaN
521,523,AV Wankhade,14-Mar-92,Right_Hand,NaN,India,0,NaN
522,524,B Aparajith,8-Jul-94,Right_Hand,Right-arm offbreak,India,0,NaN

In [32]:
df.columns

Index(['Player_Id', 'Player_Name', 'DOB', 'Batting_Hand', 'Bowling_Skill',
       'Country', 'Is_Umpire', 'Unnamed: 7'],
      dtype='object')

In [33]:
df['Player_Id']

0        1
1        2
2        3
3        4
4        5
      ...
518    519
519    520
520    521
521    523
522    524
Name: Player_Id, Length: 523, dtype: int64

In [34]:
type(df['Player_Id'])
#if you have only column to access then that type data is called series data

pandas.core.series.Series

In [35]:
type(df[['Player_Id']])
# you will put the data in double square brcaket , You will get the data frame data

pandas.core.frame.DataFrame

In [36]:
df[['Player_Id']]

     Player_Id
0            1
1            2
2            3
3            4
4            5
..         ...
518        519
519        520
520        521
521        523
522        524

[523 rows x 1 columns]

In [37]:
# but if you want to fetch more than one column it will give the error message
df['Player_Id','Player_Name']

KeyError: ('Player_Id', 'Player_Name')

In [38]:
# but these all column, you will provide in the list then , there is no any error
df[['Player_Id','Player_Name']]

     Player_Id      Player_Name
0            1       SC Ganguly
1            2      BB McCullum
2            3       RT Ponting
3            4        DJ Hussey
4            5  Mohammad Hafeez
..         ...              ...
518        519      Subroto Das
519        520     K Srinivasan
520        521        VK Sharma
521        523      AV Wankhade
522        524      B Aparajith

[523 rows x 2 columns]

In [39]:
# order doesn't matters 
df[['Country','Player_Id','Player_Name']]

         Country  Player_Id      Player_Name
0          India          1       SC Ganguly
1    New Zealand          2      BB McCullum
2      Australia          3       RT Ponting
3      Australia          4        DJ Hussey
4       Pakistan          5  Mohammad Hafeez
..           ...        ...              ...
518        India        519      Subroto Das
519        India        520     K Srinivasan
520        India        521        VK Sharma
521        India        523      AV Wankhade
522        India        524      B Aparajith

[523 rows x 3 columns]

In [40]:
pd.read_excel(r'C:\Users\itnes\Downloads\sample-excel-master\LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,1) Create your Live Production Environment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,In LUSID you can segregate environments by mak...,NaN,NaN,NaN,NaN,NaN,LUSID API Knowledge Base: Scopes.,NaN,NaN
14,NaN,NaN,NaN,NaN,Each scope has a unique code which is used to ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,To manage your client's assets you will also n...,NaN,NaN,NaN,NaN,NaN,LUSID API Knowledge Base: Portfolios,NaN,NaN
16,NaN,NaN,NaN,NaN,A portfolio lives within a given scope. Each p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,"When you add a portfolio, you can specify whic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,Scope:,Production-client,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,OK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,DisplayName,Description,Code,Created,BaseCurrency,CorporateActionSourceId,AccountingMethod,SubHoldingKeys,Result
26,NaN,NaN,NaN,1.0,Pension-fund,Pension fund for new client,Pension-fund,2019-09-08 11:49:22.720000,GBP,NaN,AverageCost,NaN,Error creating portfolio with id Pension-fund ...
27,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# !pip install xlrd

In [42]:
# if you want to all access in data science package then go for always anaconda powershell direct cmd some time didn't support, It will say to install some extra package
pd.read_excel("C:/Users/itnes/Downloads/sample-excel-master/LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xls", sheet_name="Create your instrument universe")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
66,NaN,NaN,NaN,NaN,BBG0000D14P3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,BBG00FN3B5K8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,BBG000DQQNJ8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,BBG000BF6B57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,BBG000BRVH05,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df4=pd.read_html("https://www.basketball-reference.com/players/m/morrima02.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")

In [46]:
df4

[       Season   Age   Tm   Lg  Pos      G     GS    MP   FG   FGA  ...    FT%  \
 0     2011-12  22.0  PHO  NBA   PF   63.0    7.0  19.5  2.8   6.9  ...  0.717
 1     2012-13  23.0  PHO  NBA   PF   82.0   32.0  22.4  3.2   8.0  ...  0.732
 2     2013-14  24.0  PHO  NBA   PF   81.0    0.0  26.6  5.1  10.4  ...  0.792
 3     2014-15  25.0  PHO  NBA   PF   82.0   82.0  31.5  6.2  13.4  ...  0.763
 4     2015-16  26.0  TOT  NBA   PF   64.0   45.0  25.5  4.8  11.2  ...  0.735
 5     2015-16  26.0  PHO  NBA   PF   37.0   24.0  24.8  4.6  11.6  ...  0.717
 6     2015-16  26.0  WAS  NBA   PF   27.0   21.0  26.4  5.0  10.6  ...  0.764
 7     2016-17  27.0  WAS  NBA   PF   76.0   76.0  31.2  5.3  11.7  ...  0.837
 8     2017-18  28.0  WAS  NBA   PF   73.0   73.0  27.0  4.5   9.4  ...  0.820
 9     2018-19  29.0  TOT  NBA   PF   58.0   16.0  21.9  3.5   8.3  ...  0.772
 10    2018-19  29.0  WAS  NBA   PF   34.0   15.0  26.0  4.2   9.6  ...  0.781
 11    2018-19  29.0  OKC  NBA   PF   24.0    1.0  16.1  2.5   6.5  ...  0.737
 12    2019-20  30.0  TOT  NBA   PF   58.0   17.0  20.5  3.5   7.9  ...  0.776
 13    2019-20  30.0  DET  NBA   PF   44.0   16.0  22.5  4.0   8.8  ...  0.772
 14    2019-20  30.0  LAL  NBA   PF   14.0    1.0  14.2  2.0   4.9  ...  0.833
 15    2020-21  31.0  LAL  NBA   PF   61.0   27.0  19.7  2.5   6.2  ...  0.720
 16     Career   NaN  NaN  NBA  NaN  698.0  375.0  25.0  4.2   9.5  ...  0.776
 17        NaN   NaN  NaN  NaN  NaN    NaN    NaN   NaN  NaN   NaN  ...    NaN
 18  5 seasons   NaN  PHO  NBA  NaN  345.0  145.0  25.3  4.4  10.0  ...  0.759
 19  4 seasons   NaN  WAS  NBA  NaN  210.0  185.0  28.3  4.8  10.4  ...  0.815
 20  2 seasons   NaN  LAL  NBA  NaN   75.0   28.0  18.7  2.4   6.0  ...  0.732
 21   1 season   NaN  DET  NBA  NaN   44.0   16.0  22.5  4.0   8.8  ...  0.772
 22   1 season   NaN  OKC  NBA  NaN   24.0    1.0  16.1  2.5   6.5  ...  0.737

     ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
 0   1.1  3.3  4.4  1.0  0.7  0.7  1.1  2.8   7.4
 1   1.6  3.2  4.8  1.3  0.9  0.8  1.3  2.5   8.2
 2   1.7  4.3  6.0  1.8  0.8  0.6  1.8  2.9  13.8
 3   1.3  4.8  6.2  2.3  1.2  0.5  2.1  3.0  15.3
 4   1.1  4.4  5.5  1.9  0.9  0.5  2.1  2.9  12.0
 5   1.2  4.1  5.2  2.4  0.9  0.5  2.4  2.8  11.6
 6   1.1  4.7  5.9  1.4  0.9  0.6  1.7  3.0  12.4
 7   1.4  5.1  6.5  1.7  1.1  0.6  1.7  3.3  14.0
 8   1.0  4.6  5.6  1.9  0.8  0.5  1.7  3.0  11.5
 9   1.1  3.5  4.6  1.4  0.6  0.4  0.9  3.0   9.4
 10  1.2  3.9  5.1  1.8  0.7  0.6  1.4  3.4  11.5
 11  0.8  3.0  3.8  0.8  0.5  0.1  0.3  2.4   6.5
 12  0.7  3.1  3.8  1.3  0.5  0.3  1.3  2.3   9.7
 13  0.5  3.4  3.9  1.6  0.6  0.3  1.6  2.4  11.0
 14  1.1  2.1  3.2  0.6  0.4  0.4  0.4  2.1   5.3
 15  0.8  3.6  4.4  1.2  0.4  0.3  0.9  1.7   6.7
 16  1.2  4.0  5.3  1.6  0.8  0.5  1.5  2.8  11.0
 17  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 18  1.4  4.0  5.4  1.7  0.9  0.6  1.7  2.8  11.4
 19  1.2  4.7  5.9  1.7  0.9  0.6  1.7  3.2  12.5
 20  0.9  3.3  4.1  1.1  0.4  0.3  0.8  1.8   6.4
 21  0.5  3.4  3.9  1.6  0.6  0.3  1.6  2.4  11.0
 22  0.8  3.0  3.8  0.8  0.5  0.1  0.3  2.4   6.5

 [23 rows x 30 columns],
       Season   Age   Tm   Lg  Pos     G    GS    MP   FG   FGA  ...    FT%  \
 0    2016-17  27.0  WAS  NBA   PF  13.0  13.0  28.7  4.5  11.2  ...  0.806
 1    2017-18  28.0  WAS  NBA   PF   6.0   6.0  30.2  4.0   8.2  ...  0.900
 2    2018-19  29.0  OKC  NBA   PF   5.0   0.0  11.8  1.0   3.2  ...  0.778
 3    2019-20  30.0  LAL  NBA   PF  21.0   2.0  18.3  2.1   4.7  ...  0.778
 4    2020-21  31.0  LAL  NBA   PF   4.0   1.0   9.5  0.5   2.3  ...  0.667
 5     Career   NaN  NaN  NBA  NaN  49.0  22.0  21.1  2.7   6.5  ...  0.800
 6        NaN   NaN  NaN  NaN  NaN   NaN   NaN   NaN  NaN   NaN  ...    NaN
 7  2 seasons   NaN  LAL  NBA  NaN  25.0   3.0  16.9  1.8   4.3  ...  0.733
 8  2 seasons   NaN  WAS  NBA  NaN  19.0  19.0  29.2  4.4  10.2  ...  0.829
 9   1 season   NaN  OKC  NBA  NaN   5.0   0.0  11.8  1.0   3.2  ...  0.778

    ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
 0  1.4  5.0  6.4  1.7  0.9  1.3  1.6  3.5  12.1
 1  2.3  5.2  7.5  1.7  0.7  0.8  1.0  3.7   9.8
 2  0.8  1.8  2.6  1.0  0.2  0.6  0.4  1.8   3.8
 3  0.6  2.5  3.0  1.0  0.3  0.1  0.8  2.6   5.9
 4  1.0  0.0  1.0  0.8  0.0  0.3  0.5  1.5   2.3
 5  1.1  3.2  4.3  1.2  0.5  0.6  1.0  2.8   7.5
 6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN
 7  0.6  2.1  2.7  0.9  0.2  0.2  0.8  2.4   5.3
 8  1.7  5.1  6.7  1.7  0.8  1.2  1.4  3.6  11.4
 9  0.8  1.8  2.6  1.0  0.2  0.6  0.4  1.8   3.8

 [10 rows x 30 columns],
        Season   Age   Tm   Lg  Pos      G     GS       MP      FG     FGA  \
 0     2011-12  22.0  PHO  NBA   PF   63.0    7.0   1227.0   174.0   436.0
 1     2012-13  23.0  PHO  NBA   PF   82.0   32.0   1837.0   266.0   653.0
 2     2013-14  24.0  PHO  NBA   PF   81.0    0.0   2153.0   411.0   845.0
 3     2014-15  25.0  PHO  NBA   PF   82.0   82.0   2581.0   512.0  1100.0
 4     2015-16  26.0  TOT  NBA   PF   64.0   45.0   1629.0   305.0   718.0
 5     2015-16  26.0  PHO  NBA   PF   37.0   24.0    917.0   171.0   431.0
 6     2015-16  26.0  WAS  NBA   PF   27.0   21.0    712.0   134.0   287.0
 7     2016-17  27.0  WAS  NBA   PF   76.0   76.0   2374.0   406.0   889.0
 8     2017-18  28.0  WAS  NBA   PF   73.0   73.0   1968.0   330.0   687.0
 9     2018-19  29.0  TOT  NBA   PF   58.0   16.0   1270.0   204.0   484.0
 10    2018-19  29.0  WAS  NBA   PF   34.0   15.0    883.0   143.0   328.0
 11    2018-19  29.0  OKC  NBA   PF   24.0    1.0    387.0    61.0   156.0
 12    2019-20  30.0  TOT  NBA   PF   58.0   17.0   1187.0   203.0   458.0
 13    2019-20  30.0  DET  NBA   PF   44.0   16.0    988.0   175.0   389.0
 14    2019-20  30.0  LAL  NBA   PF   14.0    1.0    199.0    28.0    69.0
 15    2020-21  31.0  LAL  NBA   PF   61.0   27.0   1200.0   153.0   378.0
 16     Career   NaN  NaN  NBA  NaN  698.0  375.0  17426.0  2964.0  6648.0
 17        NaN   NaN  NaN  NaN  NaN    NaN    NaN      NaN     NaN     NaN
 18  5 seasons   NaN  PHO  NBA  NaN  345.0  145.0   8715.0  1534.0  3465.0
 19  4 seasons   NaN  WAS  NBA  NaN  210.0  185.0   5937.0  1013.0  2191.0
 20  2 seasons   NaN  LAL  NBA  NaN   75.0   28.0   1399.0   181.0   447.0
 21   1 season   NaN  DET  NBA  NaN   44.0   16.0    988.0   175.0   389.0
 22   1 season   NaN  OKC  NBA  NaN   24.0    1.0    387.0    61.0   156.0

     ...    FT%    ORB     DRB     TRB     AST    STL    BLK     TOV      PF  \
 0   ...  0.717   69.0   210.0   279.0    65.0   41.0   42.0    70.0   179.0
 1   ...  0.732  131.0   265.0   396.0   108.0   77.0   64.0   104.0   209.0
 2   ...  0.792  139.0   346.0   485.0   144.0   68.0   51.0   147.0   232.0
 3   ...  0.763  110.0   396.0   506.0   192.0  101.0   39.0   170.0   245.0
 4   ...  0.735   73.0   279.0   352.0   124.0   58.0   34.0   135.0   184.0
 5   ...  0.717   43.0   151.0   194.0    87.0   33.0   17.0    90.0   104.0
 6   ...  0.764   30.0   128.0   158.0    37.0   25.0   17.0    45.0    80.0
 7   ...  0.837  107.0   386.0   493.0   126.0   82.0   42.0   129.0   254.0
 8   ...  0.820   75.0   334.0   409.0   142.0   56.0   38.0   127.0   216.0
 9   ...  0.772   61.0   204.0   265.0    79.0   36.0   22.0    54.0   175.0
 10  ...  0.781   41.0   133.0   174.0    60.0   25.0   20.0    47.0   117.0
 11  ...  0.737   20.0    71.0    91.0    19.0   11.0    2.0     7.0    58.0
 12  ...  0.776   40.0   178.0   218.0    77.0   31.0   17.0    76.0   133.0
 13  ...  0.772   24.0   149.0   173.0    69.0   26.0   11.0    70.0   104.0
 14  ...  0.833   16.0    29.0    45.0     8.0    5.0    6.0     6.0    29.0
 15  ...  0.720   48.0   218.0   266.0    73.0   22.0   19.0    54.0   105.0
 16  ...  0.776  853.0  2816.0  3669.0  1130.0  572.0  368.0  1066.0  1932.0
 17  ...    NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN     NaN
 18  ...  0.759  492.0  1368.0  1860.0   596.0  320.0  213.0   581.0   969.0
 19  ...  0.815  253.0   981.0  1234.0   365.0  188.0  117.0   348.0   667.0
 20  ...  0.732   64.0   247.0   311.0    81.0   27.0   25.0    60.0   134.0
 21  ...  0.772   24.0   149.0   173.0    69.0   26.0   11.0    70.0   104.0
 22  ...  0.737   20.0    71.0    91.0    19.0   11.0    2.0     7.0    58.0

        PTS
 0    467.0
 1    670.0
 2   1115.0
 3   1258.0
 4    765.0
 5    430.0
 6    335.0
 7   1063.0
 8    841.0
 9    547.0
 10   391.0
 11   156.0
 12   560.0
 13   486.0
 14    74.0
 15   407.0
 16  7693.0
 17     NaN
 18  3940.0
 19  2630.0
 20   481.0
 21   486.0
 22   156.0

 [23 rows x 30 columns],
       Season   Age   Tm   Lg  Pos     G    GS      MP     FG    FGA  ...  \
 0    2016-17  27.0  WAS  NBA   PF  13.0  13.0   373.0   59.0  145.0  ...
 1    2017-18  28.0  WAS  NBA   PF   6.0   6.0   181.0   24.0   49.0  ...
 2    2018-19  29.0  OKC  NBA   PF   5.0   0.0    59.0    5.0   16.0  ...
 3    2019-20  30.0  LAL  NBA   PF  21.0   2.0   385.0   44.0   98.0  ...
 4    2020-21  31.0  LAL  NBA   PF   4.0   1.0    38.0    2.0    9.0  ...
 5     Career   NaN  NaN  NBA  NaN  49.0  22.0  1036.0  134.0  317.0  ...
 6        NaN   NaN  NaN  NaN  NaN   NaN   NaN     NaN    NaN    NaN  ...
 7  2 seasons   NaN  LAL  NBA  NaN  25.0   3.0   423.0   46.0  107.0  ...
 8  2 seasons   NaN  WAS  NBA  NaN  19.0  19.0   554.0   83.0  194.0  ...
 9   1 season   NaN  OKC  NBA  NaN   5.0   0.0    59.0    5.0   16.0  ...

      FT%   ORB    DRB    TRB   AST   STL   BLK   TOV     PF    PTS
 0  0.806  18.0   65.0   83.0  22.0  12.0  17.0  21.0   46.0  157.0
 1  0.900  14.0   31.0   45.0  10.0   4.0   5.0   6.0   22.0   59.0
 2  0.778   4.0    9.0   13.0   5.0   1.0   3.0   2.0    9.0   19.0
 3  0.778  12.0   52.0   64.0  20.0   6.0   3.0  17.0   54.0  124.0
 4  0.667   4.0    0.0    4.0   3.0   0.0   1.0   2.0    6.0    9.0
 5  0.800  52.0  157.0  209.0  60.0  23.0  29.0  48.0  137.0  368.0
 6    NaN   NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN    NaN
 7  0.733  16.0   52.0   68.0  23.0   6.0   4.0  19.0   60.0  133.0
 8  0.829  32.0   96.0  128.0  32.0  16.0  22.0  27.0   68.0  216.0
 9  0.778   4.0    9.0   13.0   5.0   1.0   3.0   2.0    9.0   19.0

 [10 rows x 30 columns],
        Season   Age   Tm   Lg  Pos      G       MP   PER    TS%   3PAr  ...  \
 0     2011-12  22.0  PHO  NBA   PF   63.0   1227.0  12.1  0.484  0.284  ...
 1     2012-13  23.0  PHO  NBA   PF   82.0   1837.0  12.6  0.473  0.205  ...
 2     2013-14  24.0  PHO  NBA   PF   81.0   2153.0  18.4  0.564  0.128  ...
 3     2014-15  25.0  PHO  NBA   PF   82.0   2581.0  15.8  0.523  0.163  ...
 4     2015-16  26.0  TOT  NBA   PF   64.0   1629.0  12.2  0.489  0.216  ...
 5     2015-16  26.0  PHO  NBA   PF   37.0    917.0  10.8  0.456  0.176  ...
 6     2015-16  26.0  WAS  NBA   PF   27.0    712.0  14.0  0.538  0.275  ...
 7     2016-17  27.0  WAS  NBA   PF   76.0   2374.0  13.7  0.540  0.220  ...
 8     2017-18  28.0  WAS  NBA   PF   73.0   1968.0  13.2  0.566  0.301  ...
 9     2018-19  29.0  TOT  NBA   PF   58.0   1270.0  11.7  0.521  0.419  ...
 10    2018-19  29.0  WAS  NBA   PF   34.0    883.0  12.3  0.543  0.439  ...
 11    2018-19  29.0  OKC  NBA   PF   24.0    387.0  10.4  0.475  0.378  ...
 12    2019-20  30.0  TOT  NBA   PF   58.0   1187.0  12.5  0.565  0.498  ...
 13    2019-20  30.0  DET  NBA   PF   44.0    988.0  12.7  0.573  0.486  ...
 14    2019-20  30.0  LAL  NBA   PF   14.0    199.0  11.5  0.516  0.565  ...
 15    2020-21  31.0  LAL  NBA   PF   61.0   1200.0   9.3  0.509  0.553  ...
 16     Career   NaN  NaN  NBA  NaN  698.0  17426.0  13.6  0.526  0.262  ...
 17        NaN   NaN  NaN  NaN  NaN    NaN      NaN   NaN    NaN    NaN  ...
 18  5 seasons   NaN  PHO  NBA  NaN  345.0   8715.0  14.7  0.511  0.179  ...
 19  4 seasons   NaN  WAS  NBA  NaN  210.0   5937.0  13.4  0.548  0.286  ...
 20  2 seasons   NaN  LAL  NBA  NaN   75.0   1399.0   9.6  0.510  0.555  ...
 21   1 season   NaN  DET  NBA  NaN   44.0    988.0  12.7  0.573  0.486  ...
 22   1 season   NaN  OKC  NBA  NaN   24.0    387.0  10.4  0.475  0.378  ...

     Unnamed: 19  OWS   DWS    WS  WS/48  Unnamed: 24  OBPM  DBPM  BPM  VORP
 0           NaN  0.1   1.4   1.5  0.059          NaN  -2.6   0.5 -2.1   0.0
 1           NaN -0.2   1.9   1.7  0.044          NaN  -2.2   0.2 -1.9   0.0
 2           NaN  4.0   2.4   6.4  0.143          NaN   0.8   0.2  1.0   1.6
 3           NaN  1.8   2.7   4.6  0.085          NaN  -0.5   0.2 -0.3   1.1
 4           NaN -1.2   1.7   0.5  0.015          NaN  -2.3  -0.1 -2.4  -0.2
 5           NaN -1.3   0.8  -0.5 -0.029          NaN  -3.1  -0.5 -3.7  -0.4
 6           NaN  0.2   0.9   1.1  0.072          NaN  -1.3   0.5 -0.9   0.2
 7           NaN  1.6   2.5   4.1  0.083          NaN  -1.4  -0.1 -1.5   0.3
 8           NaN  1.2   2.1   3.3  0.080          NaN  -1.3   0.1 -1.3   0.4
 9           NaN  0.6   1.1   1.6  0.061          NaN  -2.1  -0.6 -2.7  -0.2
 10          NaN  0.4   0.5   0.9  0.051          NaN  -1.8  -0.9 -2.7  -0.2
 11          NaN  0.2   0.5   0.7  0.083          NaN  -2.8   0.1 -2.8  -0.1
 12          NaN  0.5   1.0   1.4  0.058          NaN  -1.1  -0.9 -2.0   0.0
 13          NaN  0.3   0.7   1.0  0.049          NaN  -1.1  -1.0 -2.1   0.0
 14          NaN  0.2   0.3   0.4  0.106          NaN  -1.3  -0.1 -1.4   0.0
 15          NaN -0.2   1.8   1.6  0.062          NaN  -2.8  -0.2 -3.0  -0.3
 16          NaN  8.1  18.7  26.7  0.074          NaN  -1.4   0.0 -1.4   2.7
 17          NaN  NaN   NaN   NaN    NaN          NaN   NaN   NaN  NaN   NaN
 18          NaN  4.4   9.2  13.6  0.075          NaN  -1.1   0.1 -0.9   2.3
 19          NaN  3.3   6.1   9.4  0.076          NaN  -1.4  -0.1 -1.5   0.7
 20          NaN -0.1   2.1   2.0  0.069          NaN  -2.6  -0.2 -2.7  -0.3
 21          NaN  0.3   0.7   1.0  0.049          NaN  -1.1  -1.0 -2.1   0.0
 22          NaN  0.2   0.5   0.7  0.083          NaN  -2.8   0.1 -2.8  -0.1

 [23 rows x 29 columns],
       Season   Age   Tm   Lg  Pos     G      MP   PER    TS%   3PAr  ...  \
 0    2016-17  27.0  WAS  NBA   PF  13.0   373.0  12.3  0.495  0.262  ...
 1    2017-18  28.0  WAS  NBA   PF   6.0   181.0  13.5  0.552  0.245  ...
 2    2018-19  29.0  OKC  NBA   PF   5.0    59.0  11.4  0.476  0.438  ...
 3    2019-20  30.0  LAL  NBA   PF  21.0   385.0   8.8  0.608  0.704  ...
 4    2020-21  31.0  LAL  NBA   PF   4.0    38.0   3.9  0.387  0.444  ...
 5     Career   NaN  NaN  NBA  NaN  49.0  1036.0  10.8  0.532  0.410  ...
 6        NaN   NaN  NaN  NaN  NaN   NaN     NaN   NaN    NaN    NaN  ...
 7  2 seasons   NaN  LAL  NBA  NaN  25.0   423.0   8.3  0.585  0.682  ...
 8  2 seasons   NaN  WAS  NBA  NaN  19.0   554.0  12.7  0.509  0.258  ...
 9   1 season   NaN  OKC  NBA  NaN   5.0    59.0  11.4  0.476  0.438  ...

    Unnamed: 19  OWS  DWS   WS  WS/48  Unnamed: 24  OBPM  DBPM  BPM  VORP
 0          NaN -0.1  0.5  0.4  0.052          NaN  -1.4   0.2 -1.2   0.1
 1          NaN  0.2  0.1  0.4  0.096          NaN  -0.6   0.4 -0.2   0.1
 2          NaN  0.0  0.1  0.1  0.078          NaN  -2.5   2.1 -0.4   0.0
 3          NaN  0.3  0.4  0.7  0.083          NaN  -2.0   0.3 -1.7   0.0
 4          NaN  0.0  0.0  0.0 -0.023          NaN  -5.8  -1.3 -7.1   0.0
 5          NaN  0.5  1.0  1.5  0.070          NaN  -1.7   0.4 -1.3   0.2
 6          NaN  NaN  NaN  NaN    NaN          NaN   NaN   NaN  NaN   NaN
 7          NaN  0.3  0.4  0.7  0.074          NaN  -2.3   0.2 -2.1   0.0
 8          NaN  0.2  0.6  0.8  0.067          NaN  -1.1   0.3 -0.8   0.2
 9          NaN  0.0  0.1  0.1  0.078          NaN  -2.5   2.1 -0.4   0.0

 [10 rows x 29 columns]]

In [47]:
type(df4)

list

In [48]:
len(df4)

6

In [49]:
df4[0]

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2011-12,22.0,PHO,NBA,PF,63.0,7.0,19.5,2.8,6.9,...,0.717,1.1,3.3,4.4,1.0,0.7,0.7,1.1,2.8,7.4
1,2012-13,23.0,PHO,NBA,PF,82.0,32.0,22.4,3.2,8.0,...,0.732,1.6,3.2,4.8,1.3,0.9,0.8,1.3,2.5,8.2
2,2013-14,24.0,PHO,NBA,PF,81.0,0.0,26.6,5.1,10.4,...,0.792,1.7,4.3,6.0,1.8,0.8,0.6,1.8,2.9,13.8
3,2014-15,25.0,PHO,NBA,PF,82.0,82.0,31.5,6.2,13.4,...,0.763,1.3,4.8,6.2,2.3,1.2,0.5,2.1,3.0,15.3
4,2015-16,26.0,TOT,NBA,PF,64.0,45.0,25.5,4.8,11.2,...,0.735,1.1,4.4,5.5,1.9,0.9,0.5,2.1,2.9,12.0
5,2015-16,26.0,PHO,NBA,PF,37.0,24.0,24.8,4.6,11.6,...,0.717,1.2,4.1,5.2,2.4,0.9,0.5,2.4,2.8,11.6
6,2015-16,26.0,WAS,NBA,PF,27.0,21.0,26.4,5.0,10.6,...,0.764,1.1,4.7,5.9,1.4,0.9,0.6,1.7,3.0,12.4
7,2016-17,27.0,WAS,NBA,PF,76.0,76.0,31.2,5.3,11.7,...,0.837,1.4,5.1,6.5,1.7,1.1,0.6,1.7,3.3,14.0
8,2017-18,28.0,WAS,NBA,PF,73.0,73.0,27.0,4.5,9.4,...,0.820,1.0,4.6,5.6,1.9,0.8,0.5,1.7,3.0,11.5
9,2018-19,29.0,TOT,NBA,PF,58.0,16.0,21.9,3.5,8.3,...,0.772,1.1,3.5,4.6,1.4,0.6,0.4,0.9,3.0,9.4
10,2018-19,29.0,WAS,NBA,PF,34.0,15.0,26.0,4.2,9.6,...,0.781,1.2,3.9,5.1,1.8,0.7,0.6,1.4,3.4,11.5
11,2018-19,29.0,OKC,NBA,PF,24.0,1.0,16.1,2.5,6.5,...,0.737,0.8,3.0,3.8,0.8,0.5,0.1,0.3,2.4,6.5
12,2019-20,30.0,TOT,NBA,PF,58.0,17.0,20.5,3.5,7.9,...,0.776,0.7,3.1,3.8,1.3,0.5,0.3,1.3,2.3,9.7
13,2019-20,30.0,DET,NBA,PF,44.0,16.0,22.5,4.0,8.8,...,0.772,0.5,3.4,3.9,1.6,0.6,0.3,1.6,2.4,11.0
14,2019-20,30.0,LAL,NBA,PF,14.0,1.0,14.2,2.0,4.9,...,0.833,1.1,2.1,3.2,0.6,0.4,0.4,0.4,2.1,5.3
15,2020-21,31.0,LAL,NBA,PF,61.0,27.0,19.7,2.5,6.2,...,0.720,0.8,3.6,4.4,1.2,0.4,0.3,0.9,1.7,6.7
16,Career,NaN,NaN,NBA,NaN,698.0,375.0,25.0,4.2,9.5,...,0.776,1.2,4.0,5.3,1.6,0.8,0.5,1.5,2.8,11.0
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5 seasons,NaN,PHO,NBA,NaN,345.0,145.0,25.3,4.4,10.0,...,0.759,1.4,4.0,5.4,1.7,0.9,0.6,1.7,2.8,11.4
19,4 seasons,NaN,WAS,NBA,NaN,210.0,185.0,28.3,4.8,10.4,...,0.815,1.2,4.7,5.9,1.7,0.9,0.6,1.7,3.2,12.5
20,2 seasons,NaN,LAL,NBA,NaN,75.0,28.0,18.7,2.4,6.0,...,0.732,0.9,3.3,4.1,1.1,0.4,0.3,0.8,1.8,6.4
21,1 season,NaN,DET,NBA,NaN,44.0,16.0,22.5,4.0,8.8,...,0.772,0.5,3.4,3.9,1.6,0.6,0.3,1.6,2.4,11.0
22,1 season,NaN,OKC,NBA,NaN,24.0,1.0,16.1,2.5,6.5,...,0.737,0.8,3.0,3.8,0.8,0.5,0.1,0.3,2.4,6.5

In [50]:
df4[0].to_csv("Player_basktball.csv")

In [53]:
html_data = pd.read_html("https://www.basketball-reference.com/players/i/ibakase01.html?utm_source=direct&utm_medium=Share&utm_campaign=ShareTool")
for i in range(len(html_data)):
    html_data[i].to_csv(f"html_data{i}.csv", index=False)

In [51]:
pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
i="""{
"name":"Itnesh",
"phone_no":34567774647,
"company":["NSIC","MapMyIndia","Indian Railways","MSME","Infosys"]
}"""

In [64]:
import json

In [65]:
s1=json.loads(i)

In [66]:
s1

{'name': 'Itnesh',
 'phone_no': 34567774647,
 'company': ['NSIC', 'MapMyIndia', 'Indian Railways', 'MSME', 'Infosys']}

In [67]:
pd.DataFrame(s1)

     name     phone_no          company
0  Itnesh  34567774647             NSIC
1  Itnesh  34567774647       MapMyIndia
2  Itnesh  34567774647  Indian Railways
3  Itnesh  34567774647             MSME
4  Itnesh  34567774647          Infosys

In [70]:
pd.DataFrame(s1, columns=['company'])

           company
0             NSIC
1       MapMyIndia
2  Indian Railways
3             MSME
4          Infosys

# fatching the data by api by pandas
* by the help of request library

In [72]:
import requests

In [76]:
requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")
#response 200 means everything ok and i am able to get the data

In [77]:
res=requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")

In [79]:
js=res.json()

In [80]:
js

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41938',
  'id': 918098404,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3NTY2MjU4',
  'number': 41938,
  'title': 'TYP/BUG: fix CI',
  'user': {'login': 'twoertwein',
   'id': 6618166,
   'node_id': 'MDQ6VXNlcjY2MTgxNjY=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/twoertwein',
   'html_url': 'https://github.com/twoertwein',
   'followers_url': 'https://api.github.com/users/twoertwein/followers',
   'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}',
   'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions',
   'organizations_url': 'https://api.github.com/users/twoertwein/orgs',
   'repos_url': 'https://api.github.com/users/twoertwein/repos',
   'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/twoertwein/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-06-11T01:04:35Z',
  'updated_at': '2021-06-11T01:04:35Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41938',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41938',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41938.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41938.patch'},
  'body': "Fix bug introduced in https://github.com/pandas-dev/pandas/pull/41903\r\n\r\nMypy doesn't seem to like generic types with default values?",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41937',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41937/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41937/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41937/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/41937',
  'id': 918097293,
  'node_id': 'MDU6SXNzdWU5MTgwOTcyOTM=',
  'number': 41937,
  'title': 'CI: intermittent segfaults on `macOS py37_macos` run',
  'user': {'login': 'mzeitlin11',
   'id': 37011898,
   'node_id': 'MDQ6VXNlcjM3MDExODk4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/37011898?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mzeitlin11',
   'html_url': 'https://github.com/mzeitlin11',
   'followers_url': 'https://api.github.com/users/mzeitlin11/followers',
   'following_url': 'https://api.github.com/users/mzeitlin11/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mzeitlin11/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mzeitlin11/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mzeitlin11/subscriptions',
   'organizations_url': 'https://api.github.com/users/mzeitlin11/orgs',
   'repos_url': 'https://api.github.com/users/mzeitlin11/repos',
   'events_url': 'https://api.github.com/users/mzeitlin11/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mzeitlin11/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Related to Continuous Integration'},
   {'id': 1121248195,
    'node_id': 'MDU6TGFiZWwxMTIxMjQ4MTk1',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Segfault',
    'name': 'Segfault',
    'color': '36ede0',
    'default': False,
    'description': 'Non-Recoverable Error'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-06-11T01:02:31Z',
  'updated_at': '2021-06-11T01:02:58Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'body': "See https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61339&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3\r\n\r\nand https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61324&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3\r\n\r\nfor some examples on 2 different runs. I've only noticed it on this run, will look to try to see when it started (unless anyone knows :)",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41936',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41936/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41936/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41936/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41936',
  'id': 918043099,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3NTE4NDIy',
  'number': 41936,
  'title': 'CLN: Remove useless Validation functions',
  'user': {'login': 'lithomas1',
   'id': 47963215,
   'node_id': 'MDQ6VXNlcjQ3OTYzMjE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/47963215?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/lithomas1',
   'html_url': 'https://github.com/lithomas1',
   'followers_url': 'https://api.github.com/users/lithomas1/followers',
   'following_url': 'https://api.github.com/users/lithomas1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/lithomas1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/lithomas1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/lithomas1/subscriptions',
   'organizations_url': 'https://api.github.com/users/lithomas1/orgs',
   'repos_url': 'https://api.github.com/users/lithomas1/repos',
   'events_url': 'https://api.github.com/users/lithomas1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/lithomas1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-06-10T23:24:06Z',
  'updated_at': '2021-06-10T23:31:21Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41936',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41936',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41936.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41936.patch'},
  'body': '- [ ] closes #xxxx\r\n- [ ] tests added / passed\r\n- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [ ] whatsnew entry\r\n\r\nNot sure what the point of these were.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41935',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41935/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41935/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41935/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/41935',
  'id': 918038987,
  'node_id': 'MDU6SXNzdWU5MTgwMzg5ODc=',
  'number': 41935,
  'title': 'CI: py 3.10 build failing',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'},
   {'id': 2955636717,
    'node_id': 'MDU6TGFiZWwyOTU1NjM2NzE3',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Python%203.10',
    'name': 'Python 3.10',
    'color': 'fef2c0',
    'default': False,
    'description': 'Python dev version'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-06-10T23:17:19Z',
  'updated_at': '2021-06-11T00:35:05Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'body': '@seberg this build is using numpy 1.22dev, looks like a bunch of the failures are raising in `np.iinfo(np.int64).max`\r\n\r\n```\r\n    return np.iinfo(np.int64).max\r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\n\r\nself = <[AttributeError("\'iinfo\' object has no attribute \'kind\'") raised in repr()] iinfo object at 0x7f986b9aa830>\r\nint_type = <class \'numpy.int64\'>\r\n\r\n    def __init__(self, int_type):\r\n        try:\r\n            self.dtype = numeric.dtype(int_type)\r\n        except TypeError:\r\n>           self.dtype = numeric.dtype(type(int_type))\r\nE           TypeError: \'numpy.dtype[bool_]\' object is not callable\r\n\r\n/opt/hostedtoolcache/Python/3.10.0-beta.2/x64/lib/python3.10/site-packages/numpy/core/getlimits.py:518: TypeError\r\n```',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41934',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41934/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41934/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41934/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41934',
  'id': 917978521,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3NDYwNjIw',
  'number': 41934,
  'title': 'BUG: IntervalIndex.get_indexer with categorical both have nans',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-06-10T21:58:36Z',
  'updated_at': '2021-06-10T21:59:35Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41934',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41934',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41934.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41934.patch'},
  'body': '- [ ] closes #xxxx\r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [x] whatsnew entry\r\n\r\nStarted with moving a fastpath from IntervalIndex to the base class.  In the process found a bug in the IntervalIndex version, which is now fixed.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41933',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41933/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41933/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41933/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41933',
  'id': 917931215,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3NDE3MDQ3',
  'number': 41933,
  'title': 'BUG: CategoricalIndex.get_loc(np.nan)',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2021-06-10T21:13:41Z',
  'updated_at': '2021-06-10T21:14:38Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41933',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41933',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41933.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41933.patch'},
  'body': '- [ ] closes #xxxx\r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n- [x] whatsnew entry\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41932',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41932/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41932/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41932/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41932',
  'id': 917893983,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3MzgyOTE1',
  'number': 41932,
  'title': 'TST: Add tests for numeric_only default behaviour (GH41351)',
  'user': {'login': 'michaelneururer',
   'id': 8530527,
   'node_id': 'MDQ6VXNlcjg1MzA1Mjc=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8530527?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/michaelneururer',
   'html_url': 'https://github.com/michaelneururer',
   'followers_url': 'https://api.github.com/users/michaelneururer/followers',
   'following_url': 'https://api.github.com/users/michaelneururer/following{/other_user}',
   'gists_url': 'https://api.github.com/users/michaelneururer/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/michaelneururer/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/michaelneururer/subscriptions',
   'organizations_url': 'https://api.github.com/users/michaelneururer/orgs',
   'repos_url': 'https://api.github.com/users/michaelneururer/repos',
   'events_url': 'https://api.github.com/users/michaelneururer/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/michaelneururer/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2021-06-10T20:41:54Z',
  'updated_at': '2021-06-10T20:50:13Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41932',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/41932',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/41932.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/41932.patch'},
  'body': '- [x] closes #41351\r\n- [x] tests added / passed\r\n- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41931',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41931/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41931/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41931/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41931',
  'id': 917753473,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3MjUwNjE3',
  'number': 41931,
  'title': 'BUG/REF: use sorted_rank_1d for rank_2d',

In [81]:
js[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/41938/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/41938',
 'id': 918098404,
 'node_id': 'MDExOlB1bGxSZXF1ZXN0NjY3NTY2MjU4',
 'number': 41938,
 'title': 'TYP/BUG: fix CI',
 'user': {'login': 'twoertwein',
  'id': 6618166,
  'node_id': 'MDQ6VXNlcjY2MTgxNjY=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/twoertwein',
  'html_url': 'https://github.com/twoertwein',
  'followers_url': 'https://api.github.com/users/twoertwein/followers',
  'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}',
  'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions',
  'organizations_url': 'https://api.github.com/users/twoertwein/orgs',
  'repos_url': 'https://api.github.com/users/twoertwein/repos',
  'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/twoertwein/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2021-06-11T01:04:35Z',
 'updated_at': '2021-06-11T01:04:35Z',
 'closed_at': None,
 'author_association': 'CONTRIBUTOR',
 'active_lock_reason': None,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/41938',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/41938',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/41938.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/41938.patch'},
 'body': "Fix bug introduced in https://github.com/pandas-dev/pandas/pull/41903\r\n\r\nMypy doesn't seem to like generic types with default values?",
 'performed_via_github_app': None}

In [82]:
# we want to fatch the data of title so 
js[0]['title']

'TYP/BUG: fix CI'

In [95]:
for i in range(len(js)):
    print(js[i]['title'])

TYP/BUG: fix CI
CI: intermittent segfaults on `macOS py37_macos` run
CLN: Remove useless Validation functions
CI: py 3.10 build failing
BUG: IntervalIndex.get_indexer with categorical both have nans
BUG: CategoricalIndex.get_loc(np.nan)
TST: Add tests for numeric_only default behaviour (GH41351)
BUG/REF: use sorted_rank_1d for rank_2d
BUG: pd.Grouper cannot be reused in some cases
BUG: Timezones are not preserved in Series.mode() output
DOC: start v1.4.0 release notes
DOC: fix header level in 1.3 release notes
PERF: fix regression in reductions for boolean/integer data
DOC: add contributors to 1.3 release notes
BUG: Scalar assignment to empty dataframe with loc. Closes GH41891
REF: de-duplicate Categorical _validate_foo_value
PERF: cache _should_fallback_to_positional
REF: give rank1d/2d same nan filling
REF: de-duplicate _intersection, _difference
REF: simplify Series.__setitem__
ENH: Add subset to fillna
BUG: pytz.AmbiguousTimeError not caught in hypothesis test test_on_offset_implementations (GH41906)
BUG: pytz.AmbiguousTimeError not caught in hypothesis `test_on_offset_implementations`
Fixed file format based on coding standards
Initial draft: from_dummies
STYLE add check for future annotations
DOC: update the msgpack IO section to not refer to pyarrow.serialize
BUG: to_hdf append string column to incompatible column
[WIP] ENH: `Styler` `apply` and `applymap` over the index instead of the data
BUG: Setting column on empty DataFrame with loc / avoiding SettingWithCopyWarning for potentially empty DataFrames/copies/views

In [97]:
pd.DataFrame(js, columns=['url','title'])

,url,title
0,https://api.github.com/repos/pandas-dev/pandas...,TYP/BUG: fix CI
1,https://api.github.com/repos/pandas-dev/pandas...,CI: intermittent segfaults on `macOS py37_maco...
2,https://api.github.com/repos/pandas-dev/pandas...,CLN: Remove useless Validation functions
3,https://api.github.com/repos/pandas-dev/pandas...,CI: py 3.10 build failing
4,https://api.github.com/repos/pandas-dev/pandas...,BUG: IntervalIndex.get_indexer with categorica...
5,https://api.github.com/repos/pandas-dev/pandas...,BUG: CategoricalIndex.get_loc(np.nan)
6,https://api.github.com/repos/pandas-dev/pandas...,TST: Add tests for numeric_only default behavi...
7,https://api.github.com/repos/pandas-dev/pandas...,BUG/REF: use sorted_rank_1d for rank_2d
8,https://api.github.com/repos/pandas-dev/pandas...,BUG: pd.Grouper cannot be reused in some cases
9,https://api.github.com/repos/pandas-dev/pandas...,BUG: Timezones are not preserved in Series.mod...
10,https://api.github.com/repos/pandas-dev/pandas...,DOC: start v1.4.0 release notes
11,https://api.github.com/repos/pandas-dev/pandas...,DOC: fix header level in 1.3 release notes
12,https://api.github.com/repos/pandas-dev/pandas...,PERF: fix regression in reductions for boolean...
13,https://api.github.com/repos/pandas-dev/pandas...,DOC: add contributors to 1.3 release notes
14,https://api.github.com/repos/pandas-dev/pandas...,BUG: Scalar assignment to empty dataframe with...
15,https://api.github.com/repos/pandas-dev/pandas...,REF: de-duplicate Categorical _validate_foo_value
16,https://api.github.com/repos/pandas-dev/pandas...,PERF: cache _should_fallback_to_positional
17,https://api.github.com/repos/pandas-dev/pandas...,REF: give rank1d/2d same nan filling
18,https://api.github.com/repos/pandas-dev/pandas...,"REF: de-duplicate _intersection, _difference"
19,https://api.github.com/repos/pandas-dev/pandas...,REF: simplify Series.__setitem__
20,https://api.github.com/repos/pandas-dev/pandas...,ENH: Add subset to fillna
21,https://api.github.com/repos/pandas-dev/pandas...,BUG: pytz.AmbiguousTimeError not caught in hyp...
22,https://api.github.com/repos/pandas-dev/pandas...,BUG: pytz.AmbiguousTimeError not caught in hyp...
23,https://api.github.com/repos/pandas-dev/pandas...,Fixed file format based on coding standards
24,https://api.github.com/repos/pandas-dev/pandas...,Initial draft: from_dummies
25,https://api.github.com/repos/pandas-dev/pandas...,STYLE add check for future annotations
26,https://api.github.com/repos/pandas-dev/pandas...,DOC: update the msgpack IO section to not refe...
27,https://api.github.com/repos/pandas-dev/pandas...,BUG: to_hdf append string column to incompatib...
28,https://api.github.com/repos/pandas-dev/pandas...,[WIP] ENH: `Styler` `apply` and `applymap` ove...
29,https://api.github.com/repos/pandas-dev/pandas...,BUG: Setting column on empty DataFrame with lo...

In [98]:
df5=pd.DataFrame(js)

In [99]:
df5.to_csv('json_dump.csv')

In [105]:
js[0]['user']

{'login': 'twoertwein',
 'id': 6618166,
 'node_id': 'MDQ6VXNlcjY2MTgxNjY=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/6618166?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/twoertwein',
 'html_url': 'https://github.com/twoertwein',
 'followers_url': 'https://api.github.com/users/twoertwein/followers',
 'following_url': 'https://api.github.com/users/twoertwein/following{/other_user}',
 'gists_url': 'https://api.github.com/users/twoertwein/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/twoertwein/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/twoertwein/subscriptions',
 'organizations_url': 'https://api.github.com/users/twoertwein/orgs',
 'repos_url': 'https://api.github.com/users/twoertwein/repos',
 'events_url': 'https://api.github.com/users/twoertwein/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/twoertwein/received_events',
 'type': 'User',
 'site_admin': False}

In [113]:
# list=[]
# for i in range(len(js)):
#         list.append(js[i]['user'])
# pd.DataFrame(list)

In [114]:
pd.DataFrame(js[i]['user'] for i in range(len(js)))

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,twoertwein,6618166,MDQ6VXNlcjY2MTgxNjY=,https://avatars.githubusercontent.com/u/661816...,,https://api.github.com/users/twoertwein,https://github.com/twoertwein,https://api.github.com/users/twoertwein/followers,https://api.github.com/users/twoertwein/follow...,https://api.github.com/users/twoertwein/gists{...,https://api.github.com/users/twoertwein/starre...,https://api.github.com/users/twoertwein/subscr...,https://api.github.com/users/twoertwein/orgs,https://api.github.com/users/twoertwein/repos,https://api.github.com/users/twoertwein/events...,https://api.github.com/users/twoertwein/receiv...,User,False
1,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
2,lithomas1,47963215,MDQ6VXNlcjQ3OTYzMjE1,https://avatars.githubusercontent.com/u/479632...,,https://api.github.com/users/lithomas1,https://github.com/lithomas1,https://api.github.com/users/lithomas1/followers,https://api.github.com/users/lithomas1/followi...,https://api.github.com/users/lithomas1/gists{/...,https://api.github.com/users/lithomas1/starred...,https://api.github.com/users/lithomas1/subscri...,https://api.github.com/users/lithomas1/orgs,https://api.github.com/users/lithomas1/repos,https://api.github.com/users/lithomas1/events{...,https://api.github.com/users/lithomas1/receive...,User,False
3,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
4,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
5,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
6,michaelneururer,8530527,MDQ6VXNlcjg1MzA1Mjc=,https://avatars.githubusercontent.com/u/853052...,,https://api.github.com/users/michaelneururer,https://github.com/michaelneururer,https://api.github.com/users/michaelneururer/f...,https://api.github.com/users/michaelneururer/f...,https://api.github.com/users/michaelneururer/g...,https://api.github.com/users/michaelneururer/s...,https://api.github.com/users/michaelneururer/s...,https://api.github.com/users/michaelneururer/orgs,https://api.github.com/users/michaelneururer/r...,https://api.github.com/users/michaelneururer/e...,https://api.github.com/users/michaelneururer/r...,User,False
7,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
8,mimakaev,9454715,MDQ6VXNlcjk0NTQ3MTU=,https://avatars.githubusercontent.com/u/945471...,,https://api.github.com/users/mimakaev,https://github.com/mimakaev,https://api.github.com/users/mimakaev/followers,https://api.github.com/users/mimakaev/followin...,https://api.github.com/users/mimakaev/gists{/g...,https://api.github.com/users/mimakaev/starred{...,https://api.github.com/users/mimakaev/subscrip...,https://api.github.com/users/mimakaev/orgs,https://api.github.com/users/mimakaev/repos,https://api.github.com/users/mimakaev/events{/...,https://api.github.com/users/mimakaev/received...,User,False
9,willsthompson,1315884,MDQ6VXNlcjEzMTU4ODQ=,https://avatars.githubusercontent.com/u/131588...,,https://api.github.com/users/willsthompson,https://github.com/willsthompson,https://api.github.com/users/willsthompson/fol...,https://api.github.com/users/willsthompson/fol...,https://api.github.com/users/willsthompson/gis...,https://api.github.com/users/willsthompson/sta...,https://api.github.com/users/willsthompson/sub...,https://api.github.com/users/willsthompson/orgs,https://api.github.com/users/willsthompson/repos,https://api.github.com/users/willsthompson/eve...,https://api.github.com/users/willsthompson/rec...,User,False
10,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
11,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
12,jorisvandenbossche,1020496,MDQ6VXNlcjEwMjA0OTY=,https://avatars.githubusercontent.com/u/102049...,,https://api.github.com/users/jorisvandenbossche,https://github.com/jorisvandenbossche,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,User,False
13,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
14,klieret,13602468,MDQ6VXNlcjEzNjAyNDY4,https://avatars.githubusercontent.com/u/136024...,,https://api.github.com/users/klieret,https://github.com/klieret,https://api.github.com/users/klieret/followers,https://api.github.com/users/klieret/following...,https://api.github.com/users/klieret/gists{/gi...,https://api.github.com/users/klieret/starred{/...,https://api.github.com/users/klieret/subscript...,https://api.github.com/users/klieret/orgs,https://api.github.com/users/klieret/repos,https://api.github.com/users/klieret/events{/p...,https://api.github.com/users/klieret/received_...,User,False
15,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
16,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
17,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
18,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
19,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
20,eikevons,1563963,MDQ6VXNlcjE1NjM5NjM=,https://avatars.githubusercontent.com/u/156396...,,https://api.github.com/users/eikevons,https://github.com/eikevons,https://api.github.com/users/eikevons/followers,https://api.github.com/users/eikevons/followin...,https://api.github.com/users/eikevons/gists{/g...,https://api.github.com/users/eikevons/starred{...,https://api.github.com/users/eikevons/subscrip...,https://api.github.com/users/eikevons/orgs,https://api.github.com/users/eikevons/repos,https://api.github.com/users/eikevons/events{/...,https://api.github.com/users/eikevons/received...,User,False
21,jackzyliu,5811028,MDQ6VXNlcjU4MTEwMjg=,https://avatars.githubusercontent.com/u/581102...,,https://api.github.com/users/jackzyliu,https://github.com/jackzyliu,https://api.github.com/users/jackzyliu/followers,https://api.github.com/users/jackzyliu/followi...,https://api.github.com/users/jackzyliu/gists{/...,https://api.github.com/users/jackzyliu/starred...,https://api.github.com/users/jackzyliu/subscri...,https://api.github.com/users/jackzyliu/orgs,https://api.github.com/users/jackzyliu/repos,https://api.github.com/users/jackzyliu/events{...,https://api.github.com/users/jackzyliu/receive...,User,False
22,jackzyliu,5811028,MDQ6VXNlcjU4MTEwMjg=,https://avatars.githubusercontent.com/u/581102...,,https://api.github.com/users/jackzyliu,https://github.com/jackzyliu,https://api.github.com/users/jackzyliu/followers,https://api.github.com/users/jackzyliu/followi...,https://api.github.com/users/jackzyliu/gists{/...,https://api.github.com/users/jackzyliu/starred...,https://api.github.com/users/jackzyliu/subscri...,https://api.github.com/users/jackzyliu/orgs,https://api.github.com/users/jackzyliu/repos,https://api.github.com/users/jackzyliu/events{...,https://api.github.com/users/jackzyliu/receive...,User,False
23,ranOutaNames,47838927,MDQ6VXNlcjQ3ODM4OTI3,https://avatars.githubusercontent.com/u/478389...,,https://api.github.com/users/ranOutaNames,https://github.com/ranOutaNames,https://api.github.com/users/ranOutaNames/foll...,https://api.github.com/users/ranOutaNames/foll...,https://api.github.com/users/ranOutaNames/gist...,https://api.github.com/users/ranOutaNames/star...,https://api.github.com/users/ranOutaNames/subs...,https://api.github.com/users/ranOutaNames/orgs,https://api.github.com/users/ranOutaNames/repos,https://api.github.com/users/ranOutaNames/even...,https://api.github.com/users/ranOutaNames/rece...,User,False
24,pckSF,54398132,MDQ6VXNlcjU0Mzk4MTMy,https://avatars.githubusercontent.com/u/543981...,,https://api.github.com/users/pckSF,https://github.com/pckSF,https://api.github.com/users/pckSF/followers,https://api.github.com/users/pckSF/following{/...,https://api.github.com/users/pckSF/gists{/gist...,https://api.github.com/users/pckSF/starred{/ow...,https://api.github.com/users/pckSF/subscriptions,https://api.github.com/users/pckSF/orgs,https://api.github.com/users/pckSF/repos,https://api.github.com/users/pckSF/events{/pri...,https://api.github.com/users/pckSF/received_ev...,User,False
25,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,False
26,jorisvandenbossche,1020496,MDQ6VXNlcjEwMjA0OTY=,https://avatars.githubusercontent.com/u/102049...,,https://api.github.com/users/jorisvandenbossche,https://github.com/jorisvandenbossche,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,User,False
27,lrepiton,6302028,MDQ6VXNlcjYzMDIwMjg=,https://avatars.githubusercontent.com/u/630202...,,https://api.github.com/users/lrepiton,https://github.com/lrepiton,https://api.github.com/users/lrepiton/followers,https://api.github.com/users/lrepiton/followin...,https://api.github.com/users/lrepiton/gists{/g...,https://api.github.com/users/lrepiton/starred{...,https://api.github.com/users/lrepiton/subscrip...,https://api.github.com/users/lrepiton/orgs,https://api.github.com/users/lrepiton/repos,https://api.github.com/users/lrepiton/events{/...,https://api.github.com/users/lrepiton/received...,User,False
28,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
29,klieret,13602468,MDQ6VXNlcjEzNjAyNDY4,https://avatars.githubusercontent.com/u/136024...,,https://api.github.com/users/klieret,https://github.com/klieret,https://api.github.com/users/klieret/followers,https://api.github.com/users/klieret/following...,https://api.github.com/users/klieret/gists{/gi...,https://api.github.com/users/klieret/starred{/...,https://api.github.com/users/klieret/subscript...,https://api.github.com/users/klieret/orgs,https://api.github.com/users/klieret/repos,https://api.github.com/users/klieret/events{/p...,https://api.github.com/users/klieret/received_...,User,False

In [118]:
#reading the json data by pandas lib
json_data=pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")
pd.DataFrame.from_records(json_data['user'])

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,site_admin
0,topper-123,26364415,MDQ6VXNlcjI2MzY0NDE1,https://avatars.githubusercontent.com/u/263644...,,https://api.github.com/users/topper-123,https://github.com/topper-123,https://api.github.com/users/topper-123/followers,https://api.github.com/users/topper-123/follow...,https://api.github.com/users/topper-123/gists{...,https://api.github.com/users/topper-123/starre...,https://api.github.com/users/topper-123/subscr...,https://api.github.com/users/topper-123/orgs,https://api.github.com/users/topper-123/repos,https://api.github.com/users/topper-123/events...,https://api.github.com/users/topper-123/receiv...,User,False
1,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
2,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
3,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
4,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
5,Swanand01,75439077,MDQ6VXNlcjc1NDM5MDc3,https://avatars.githubusercontent.com/u/754390...,,https://api.github.com/users/Swanand01,https://github.com/Swanand01,https://api.github.com/users/Swanand01/followers,https://api.github.com/users/Swanand01/followi...,https://api.github.com/users/Swanand01/gists{/...,https://api.github.com/users/Swanand01/starred...,https://api.github.com/users/Swanand01/subscri...,https://api.github.com/users/Swanand01/orgs,https://api.github.com/users/Swanand01/repos,https://api.github.com/users/Swanand01/events{...,https://api.github.com/users/Swanand01/receive...,User,False
6,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
7,realead,17513912,MDQ6VXNlcjE3NTEzOTEy,https://avatars.githubusercontent.com/u/175139...,,https://api.github.com/users/realead,https://github.com/realead,https://api.github.com/users/realead/followers,https://api.github.com/users/realead/following...,https://api.github.com/users/realead/gists{/gi...,https://api.github.com/users/realead/starred{/...,https://api.github.com/users/realead/subscript...,https://api.github.com/users/realead/orgs,https://api.github.com/users/realead/repos,https://api.github.com/users/realead/events{/p...,https://api.github.com/users/realead/received_...,User,False
8,realead,17513912,MDQ6VXNlcjE3NTEzOTEy,https://avatars.githubusercontent.com/u/175139...,,https://api.github.com/users/realead,https://github.com/realead,https://api.github.com/users/realead/followers,https://api.github.com/users/realead/following...,https://api.github.com/users/realead/gists{/gi...,https://api.github.com/users/realead/starred{/...,https://api.github.com/users/realead/subscript...,https://api.github.com/users/realead/orgs,https://api.github.com/users/realead/repos,https://api.github.com/users/realead/events{/p...,https://api.github.com/users/realead/received_...,User,False
9,swenlaur,15105451,MDQ6VXNlcjE1MTA1NDUx,https://avatars.githubusercontent.com/u/151054...,,https://api.github.com/users/swenlaur,https://github.com/swenlaur,https://api.github.com/users/swenlaur/followers,https://api.github.com/users/swenlaur/followin...,https://api.github.com/users/swenlaur/gists{/g...,https://api.github.com/users/swenlaur/starred{...,https://api.github.com/users/swenlaur/subscrip...,https://api.github.com/users/swenlaur/orgs,https://api.github.com/users/swenlaur/repos,https://api.github.com/users/swenlaur/events{/...,https://api.github.com/users/swenlaur/received...,User,False
10,jorisvandenbossche,1020496,MDQ6VXNlcjEwMjA0OTY=,https://avatars.githubusercontent.com/u/102049...,,https://api.github.com/users/jorisvandenbossche,https://github.com/jorisvandenbossche,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,User,False
11,gcaria,44147817,MDQ6VXNlcjQ0MTQ3ODE3,https://avatars.githubusercontent.com/u/441478...,,https://api.github.com/users/gcaria,https://github.com/gcaria,https://api.github.com/users/gcaria/followers,https://api.github.com/users/gcaria/following{...,https://api.github.com/users/gcaria/gists{/gis...,https://api.github.com/users/gcaria/starred{/o...,https://api.github.com/users/gcaria/subscriptions,https://api.github.com/users/gcaria/orgs,https://api.github.com/users/gcaria/repos,https://api.github.com/users/gcaria/events{/pr...,https://api.github.com/users/gcaria/received_e...,User,False
12,attack68,24256554,MDQ6VXNlcjI0MjU2NTU0,https://avatars.githubusercontent.com/u/242565...,,https://api.github.com/users/attack68,https://github.com/attack68,https://api.github.com/users/attack68/followers,https://api.github.com/users/attack68/followin...,https://api.github.com/users/attack68/gists{/g...,https://api.github.com/users/attack68/starred{...,https://api.github.com/users/attack68/subscrip...,https://api.github.com/users/attack68/orgs,https://api.github.com/users/attack68/repos,https://api.github.com/users/attack68/events{/...,https://api.github.com/users/attack68/received...,User,False
13,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
14,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/106470...,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/followi...,https://api.github.com/users/mroeschke/gists{/...,https://api.github.com/users/mroeschke/starred...,https://api.github.com/users/mroeschke/subscri...,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{...,https://api.github.com/users/mroeschke/receive...,User,False
15,huonw,1203825,MDQ6VXNlcjEyMDM4MjU=,https://avatars.githubusercontent.com/u/120382...,,https://api.github.com/users/huonw,https://github.com/huonw,https://api.github.com/users/huonw/followers,https://api.github.com/users/huonw/following{/...,https://api.github.com/users/huonw/gists{/gist...,https://api.github.com/users/huonw/starred{/ow...,https://api.github.com/users/huonw/subscriptions,https://api.github.com/users/huonw/orgs,https://api.github.com/users/huonw/repos,https://api.github.com/users/huonw/events{/pri...,https://api.github.com/users/huonw/received_ev...,User,False
16,ForestMars,402773,MDQ6VXNlcjQwMjc3Mw==,https://avatars.githubusercontent.com/u/402773...,,https://api.github.com/users/ForestMars,https://github.com/ForestMars,https://api.github.com/users/ForestMars/followers,https://api.github.com/users/ForestMars/follow...,https://api.github.com/users/ForestMars/gists{...,https://api.github.com/users/ForestMars/starre...,https://api.github.com/users/ForestMars/subscr...,https://api.github.com/users/ForestMars/orgs,https://api.github.com/users/ForestMars/repos,https://api.github.com/users/ForestMars/events...,https://api.github.com/users/ForestMars/receiv...,User,False
17,lithomas1,47963215,MDQ6VXNlcjQ3OTYzMjE1,https://avatars.githubusercontent.com/u/479632...,,https://api.github.com/users/lithomas1,https://github.com/lithomas1,https://api.github.com/users/lithomas1/followers,https://api.github.com/users/lithomas1/followi...,https://api.github.com/users/lithomas1/gists{/...,https://api.github.com/users/lithomas1/starred...,https://api.github.com/users/lithomas1/subscri...,https://api.github.com/users/lithomas1/orgs,https://api.github.com/users/lithomas1/repos,https://api.github.com/users/lithomas1/events{...,https://api.github.com/users/lithomas1/receive...,User,False
18,lithomas1,47963215,MDQ6VXNlcjQ3OTYzMjE1,https://avatars.githubusercontent.com/u/479632...,,https://api.github.com/users/lithomas1,https://github.com/lithomas1,https://api.github.com/users/lithomas1/followers,https://api.github.com/users/lithomas1/followi...,https://api.github.com/users/lithomas1/gists{/...,https://api.github.com/users/lithomas1/starred...,https://api.github.com/users/lithomas1/subscri...,https://api.github.com/users/lithomas1/orgs,https://api.github.com/users/lithomas1/repos,https://api.github.com/users/lithomas1/events{...,https://api.github.com/users/lithomas1/receive...,User,False
19,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
20,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
21,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
22,michaelneururer,8530527,MDQ6VXNlcjg1MzA1Mjc=,https://avatars.githubusercontent.com/u/853052...,,https://api.github.com/users/michaelneururer,https://github.com/michaelneururer,https://api.github.com/users/michaelneururer/f...,https://api.github.com/users/michaelneururer/f...,https://api.github.com/users/michaelneururer/g...,https://api.github.com/users/michaelneururer/s...,https://api.github.com/users/michaelneururer/s...,https://api.github.com/users/michaelneururer/orgs,https://api.github.com/users/michaelneururer/r...,https://api.github.com/users/michaelneururer/e...,https://api.github.com/users/michaelneururer/r...,User,False
23,mzeitlin11,37011898,MDQ6VXNlcjM3MDExODk4,https://avatars.githubusercontent.com/u/370118...,,https://api.github.com/users/mzeitlin11,https://github.com/mzeitlin11,https://api.github.com/users/mzeitlin11/followers,https://api.github.com/users/mzeitlin11/follow...,https://api.github.com/users/mzeitlin11/gists{...,https://api.github.com/users/mzeitlin11/starre...,https://api.github.com/users/mzeitlin11/subscr...,https://api.github.com/users/mzeitlin11/orgs,https://api.github.com/users/mzeitlin11/repos,https://api.github.com/users/mzeitlin11/events...,https://api.github.com/users/mzeitlin11/receiv...,User,False
24,mimakaev,9454715,MDQ6VXNlcjk0NTQ3MTU=,https://avatars.githubusercontent.com/u/945471...,,https://api.github.com/users/mimakaev,https://github.com/mimakaev,https://api.github.com/users/mimakaev/followers,https://api.github.com/users/mimakaev/followin...,https://api.github.com/users/mimakaev/gists{/g...,https://api.github.com/users/mimakaev/starred{...,https://api.github.com/users/mimakaev/subscrip...,https://api.github.com/users/mimakaev/orgs,https://api.github.com/users/mimakaev/repos,https://api.github.com/users/mimakaev/events{/...,https://api.github.com/users/mimakaev/received...,User,False
25,willsthompson,1315884,MDQ6VXNlcjEzMTU4ODQ=,https://avatars.githubusercontent.com/u/131588...,,https://api.github.com/users/willsthompson,https://github.com/willsthompson,https://api.github.com/users/willsthompson/fol...,https://api.github.com/users/willsthompson/fol...,https://api.github.com/users/willsthompson/gis...,https://api.github.com/users/willsthompson/sta...,https://api.github.com/users/willsthompson/sub...,https://api.github.com/users/willsthompson/orgs,https://api.github.com/users/willsthompson/repos,https://api.github.com/users/willsthompson/eve...,https://api.github.com/users/willsthompson/rec...,User,False
26,simonjayhawkins,13159005,MDQ6VXNlcjEzMTU5MDA1,https://avatars.githubusercontent.com/u/131590...,,https://api.github.com/users/simonjayhawkins,https://github.com/simonjayhawkins,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/f...,https://api.github.com/users/simonjayhawkins/g...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/s...,https://api.github.com/users/simonjayhawkins/orgs,https://api.github.com/users/simonjayhawkins/r...,https://api.github.com/users/simonjayhawkins/e...,https://api.github.com/users/simonjayhawkins/r...,User,False
27,klieret,13602468,MDQ6VXNlcjEzNjAyNDY4,https://avatars.githubusercontent.com/u/136024...,,https://api.github.com/users/klieret,https://github.com/klieret,https://api.github.com/users/klieret/followers,https://api.github.com/users/klieret/following...,https://api.github.com/users/klieret/gists{/gi...,https://api.github.com/users/klieret/starred{/...,https://api.github.com/users/klieret/subscript...,https://api.github.com/users/klieret/orgs,https://api.github.com/users/klieret/repos,https://api.github.com/users/klieret/events{/p...,https://api.github.com/users/klieret/received_...,User,False
28,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False
29,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/807896...,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/foll...,https://api.github.com/users/jbrockmendel/gist...,https://api.github.com/users/jbrockmendel/star...,https://api.github.com/users/jbrockmendel/subs...,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/even...,https://api.github.com/users/jbrockmendel/rece...,User,False

In [122]:
from_file=pd.read_csv('html_data1.csv')
# to read tne csv file

# Different type of file formate
### 1. to store the data in pickle formate
* store the data in the form for binary to converting the data into bite code i.e serialised formate
* _serde_ serrialisation and deserialisation

In [124]:
from_file.to_pickle('my_pickle')

# .H5 file , it is another binary file formate

In [125]:
h5_data= pd.HDFStore('test.h5')

In [130]:
h5_data['obj1']=from_file

C:\Users\itnes\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3418: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block1_values] [items->Index(['Season', 'Tm', 'Lg', 'Pos'], dtype='object')]

  exec(code_obj, self.user_global_ns, self.user_ns)

In [131]:
h5_data['obj1']

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2009-10,20.0,OKC,NBA,PF,6.0,0.0,25.5,3.3,5.8,...,0.700,2.2,4.3,6.5,0.3,0.3,2.0,1.0,3.2,7.8
1,2010-11,21.0,OKC,NBA,PF,17.0,17.0,28.8,3.9,8.5,...,0.825,2.8,4.5,7.3,0.2,0.2,3.1,1.2,3.8,9.8
2,2011-12,22.0,OKC,NBA,PF,20.0,20.0,28.5,4.2,8.0,...,0.722,2.4,3.4,5.8,0.6,0.6,3.0,0.6,2.9,9.8
3,2012-13,23.0,OKC,NBA,PF,11.0,11.0,33.3,5.4,12.3,...,0.792,3.5,4.8,8.4,0.7,0.0,3.0,0.6,3.5,12.8
4,2013-14,24.0,OKC,NBA,PF,17.0,17.0,34.2,5.1,8.6,...,0.765,1.8,5.0,6.8,0.7,0.6,2.5,1.2,3.2,12.1
5,2015-16,26.0,OKC,NBA,PF,18.0,18.0,33.4,4.7,9.1,...,0.750,1.3,5.0,6.3,0.6,0.8,1.3,0.5,2.8,12.0
6,2016-17,27.0,TOR,NBA,PF,10.0,10.0,30.7,6.0,13.0,...,0.846,0.9,5.6,6.5,1.4,0.4,1.7,1.1,3.7,14.3
7,2017-18,28.0,TOR,NBA,PF,10.0,9.0,26.0,3.0,7.2,...,0.818,1.3,4.6,5.9,1.1,0.1,1.3,1.6,2.1,8.7
8,2018-19,29.0,TOR,NBA,C,24.0,0.0,20.8,3.8,8.0,...,0.762,1.5,4.5,6.0,0.9,0.5,1.0,1.0,3.3,9.4
9,2019-20,30.0,TOR,NBA,C,11.0,0.0,22.8,5.7,10.0,...,1.000,1.5,6.2,7.7,1.2,0.2,1.3,1.1,2.5,14.8
10,2020-21,31.0,LAC,NBA,C,2.0,0.0,9.0,1.5,3.0,...,1.000,0.5,1.5,2.0,1.0,0.5,1.5,0.5,0.5,5.0
11,Career,NaN,NaN,NBA,NaN,146.0,102.0,28.1,4.5,8.9,...,0.792,1.9,4.7,6.5,0.7,0.4,2.0,1.0,3.1,11.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6 seasons,NaN,OKC,NBA,NaN,89.0,83.0,31.0,4.5,8.8,...,0.768,2.2,4.5,6.7,0.5,0.5,2.5,0.8,3.2,10.9
14,4 seasons,NaN,TOR,NBA,NaN,55.0,19.0,24.0,4.5,9.2,...,0.824,1.3,5.1,6.4,1.1,0.3,1.2,1.2,3.0,11.2
15,1 season,NaN,LAC,NBA,NaN,2.0,0.0,9.0,1.5,3.0,...,1.000,0.5,1.5,2.0,1.0,0.5,1.5,0.5,0.5,5.0

In [137]:
# how to insert the data in h5 file

In [138]:
h5_data.put('obj2', from_file, format='table')

In [139]:
#how to fetch the data from table

In [140]:
h5_data.select('obj2', where=['index >10 and index <14'])

,Season,Age,Tm,Lg,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
11,Career,NaN,NaN,NBA,NaN,146.0,102.0,28.1,4.5,8.9,...,0.792,1.9,4.7,6.5,0.7,0.4,2.0,1.0,3.1,11.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6 seasons,NaN,OKC,NBA,NaN,89.0,83.0,31.0,4.5,8.8,...,0.768,2.2,4.5,6.7,0.5,0.5,2.5,0.8,3.2,10.9

In [141]:
df7=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [143]:
df7.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [146]:
df7.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [147]:
df7.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [156]:
#select the data with particular data type
df7.dtypes=='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [157]:
#select only object data type
df7.dtypes[df7.dtypes=='object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [158]:
df7.dtypes[df7.dtypes=='object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [159]:
# if i want to collect that index which has the object data not any numerical data
df7[df7.dtypes[df7.dtypes=='object'].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [161]:
df10=df7[df7.dtypes[df7.dtypes=='object'].index]

In [164]:
df10.describe()

                      Name   Sex Ticket        Cabin Embarked
count                  891   891    891          204      889
unique                 891     2    681          147        3
top     Nankoff, Mr. Minko  male   1601  C23 C25 C27        S
freq                     1   577      7            4      644

In [176]:
# filter the float data type 
df7[df7.dtypes[df7.dtypes=="float64"].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [181]:
#fatch the data in name table from 5 to 10 index 
#but in range indexing data always exclude the upper limit of the condition
df7['Name'][5:10]

5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [183]:
df7[['Ticket']][5:16]

       Ticket
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406
15     248706

In [184]:
# If I need the shorted formate
sorted(df7['Ticket'])

['110152',
 '110152',
 '110152',
 '110413',
 '110413',
 '110413',
 '110465',
 '110465',
 '110564',
 '110813',
 '111240',
 '111320',
 '111361',
 '111361',
 '111369',
 '111426',
 '111427',
 '111428',
 '112050',
 '112052',
 '112053',
 '112058',
 '112059',
 '112277',
 '112379',
 '113028',
 '113043',
 '113050',
 '113051',
 '113055',
 '113056',
 '113059',
 '113501',
 '113503',
 '113505',
 '113505',
 '113509',
 '113510',
 '113514',
 '113572',
 '113572',
 '113760',
 '113760',
 '113760',
 '113760',
 '113767',
 '113773',
 '113776',
 '113776',
 '113781',
 '113781',
 '113781',
 '113781',
 '113783',
 '113784',
 '113786',
 '113787',
 '113788',
 '113789',
 '113789',
 '113792',
 '113794',
 '113796',
 '113798',
 '113798',
 '113800',
 '113803',
 '113803',
 '113804',
 '113806',
 '113806',
 '113807',
 '11668',
 '11668',
 '11751',
 '11751',
 '11752',
 '11753',
 '11755',
 '11765',
 '11767',
 '11767',
 '11769',
 '11771',
 '11774',
 '11813',
 '11967',
 '11967',
 '12233',
 '12460',
 '12749',
 '12749',
 '13049',
 '13213',
 '13214',
 '13502',
 '13502',
 '13502',
 '13507',
 '13507',
 '13509',
 '13567',
 '13568',
 '14311',
 '14312',
 '14313',
 '14973',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '1601',
 '16966',
 '16966',
 '16988',
 '17421',
 '17421',
 '17421',
 '17421',
 '17453',
 '17453',
 '17463',
 '17464',
 '17465',
 '17466',
 '17474',
 '17474',
 '17764',
 '19877',
 '19877',
 '19928',
 '19928',
 '19943',
 '19943',
 '19947',
 '19950',
 '19950',
 '19950',
 '19950',
 '19952',
 '19972',
 '19988',
 '19996',
 '19996',
 '2003',
 '211536',
 '21440',
 '218629',
 '219533',
 '220367',
 '220845',
 '220845',
 '2223',
 '223596',
 '226593',
 '226875',
 '228414',
 '229236',
 '230080',
 '230080',
 '230080',
 '230136',
 '230136',
 '230433',
 '230433',
 '230434',
 '231919',
 '231919',
 '231945',
 '233639',
 '233866',
 '234360',
 '234604',
 '234686',
 '234818',
 '236171',
 '236852',
 '236853',
 '237442',
 '237565',
 '237668',
 '237671',
 '237736',
 '237736',
 '237789',
 '237798',
 '239853',
 '239853',
 '239853',
 '239854',
 '239855',
 '239856',
 '239865',
 '239865',
 '240929',
 '24160',
 '24160',
 '24160',
 '243847',
 '243847',
 '243880',
 '244252',
 '244252',
 '244270',
 '244278',
 '244310',
 '244358',
 '244361',
 '244367',
 '244367',
 '244373',
 '248698',
 '248706',
 '248723',
 '248727',
 '248727',
 '248727',
 '248731',
 '248733',
 '248738',
 '248738',
 '248740',
 '248747',
 '250643',
 '250644',
 '250644',
 '250646',
 '250647',
 '250647',
 '250648',
 '250649',
 '250649',
 '250651',
 '250652',
 '250653',
 '250655',
 '250655',
 '2620',
 '2623',
 '2624',
 '2625',
 '2626',
 '2627',
 '2627',
 '2628',
 '2629',
 '2631',
 '26360',
 '26360',
 '2641',
 '2647',
 '2648',
 '2649',
 '2650',
 '2651',
 '2651',
 '2653',
 '2653',
 '2659',
 '2659',
 '2661',
 '2661',
 '2662',
 '2663',
 '2664',
 '2665',
 '2665',
 '2666',
 '2666',
 '2666',
 '2666',
 '2667',
 '2668',
 '2668',
 '2669',
 '26707',
 '2671',
 '2672',
 '2674',
 '2677',
 '2678',
 '2678',
 '2680',
 '2683',
 '2685',
 '2686',
 '2687',
 '2689',
 '2690',
 '2691',
 '2691',
 '2693',
 '2694',
 '2695',
 '2697',
 '2699',
 '2699',
 '2700',
 '27042',
 '27267',
 '27849',
 '28134',
 '28206',
 '28213',
 '28220',
 '28228',
 '28403',
 '28403',
 '28424',
 '28425',
 '28551',
 '28664',
 '28665',
 '29011',
 '2908',
 '2908',
 '29103',
 '29104',
 '29105',
 '29106',
 '29106',
 '29106',
 '29108',
 '2926',
 '29750',
 '29750',
 '29751',
 '3101264',
 '3101265',
 '3101267',
 '3101276',
 '3101277',
 '3101278',
 '3101278',
 '3101281',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101295',
 '3101296',
 '3101298',
 '31027',
 '31027',
 '31028',
 '312991',
 '312992',
 '312993',
 '31418',
 '315037',
 '315082',
 '315084',
 '315086',
 '315088',
 '315089',
 '315090',
 '315093',
 '315094',
 '315096',
 '315097',
 '315098',
 '315151',
 '315153',
 '323592',
 '323951',
 '324669',
 '330877',
 '330909',
 '330919',
 '330923',
 '330931',
 '330932',
 '330935',
 '330958',
 '330959',
 '330979',
 '330980',
 '334912',
 '335097',
 '335677',
 '33638',
 '336439',
 '3411',
 '341826',
 '34218',
 '342826',
 '343095',
 '343120',
 '343275',
 '343276',
 '345364',
 '345572',
 '345763',
 '345764',
 '345764',
 '345765',
 '345767',
 '345769',
 '345770',
 '345773',
 '345773',
 '345773',
 '345774',
 '345777',
 '345778',
 '345779',
 '345780',
 '345781',
 '345783',
 '3460',
 '347054',
 '347054',
 '347060',
 '347061',
 '347062',
 '347063',
 '347064',
 '347067',
 '347068',
 '347069',
 '347071',
 '347073',
 '347074',
 '347076',
 '347077',
 '347077',
 '347077',
 '347077',
 '347078',
 '347080',
 '347080',
 '347081',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347082',
 '347083',
 '347085',
 '347087',
 '347088',
 '347088',
 '347088',
 '347088',
 '347088',
 '347088',
 '347089',
 '3474',
 '347464',
 '347466',
 '347468',
 '347470',
 '347742',
 '347742',
 '347742',
 '347743',
 '348121',
 '348123',
 '348124',
 '349201',
 '349203',
 '349204',
 '349205',
 '349206',
 '349207',
 '349208',
 '349209',
 '349210',
 '349212',
 '349213',
 '349214',
 '349215',
 '349216',
 '349217',
 '349218',
 '349219',
 '349221',
 '349222',
 '349223',
 '349224',
 '349225',
 '349227',
 '349228',
 '349231',
 '349233',
 '349234',
 '349236',
 '349237',
 '349237',
 '349239',
 '349240',
 '349241',
 '349242',
 '349243',
 '349244',
 '349245',
 '349246',
 '349247',
 '349248',
 '349249',
 '349251',
 '349252',
 '349253',
 '349254',
 '349256',
 '349257',
 '349909',
 '349909',
 '349909',
 '349909',
 '349910',
 '349912',
 '350025',
 '350026',
 '350029',
 '350034',
 '350035',
 '350036',
 '350042',
 '350043',
 '350046',
 '350047',
 '350048',
 '350050',
 '350052',
 '350060',
 '350404',
 '350406',
 '350407',
 '350417',
 '35273',
 '35273',
 '35273',
 '35281',
 '35281',
 '35851',
 '35852',
 '358585',
 '358585',
 '36209',
 '362316',
 '363291',
 '363291',
 '363291',
 '363294',
 '363592',
 '364498',
 '364499',
 '364500',
 '364506',
 '364511',
 '364512',
 '364516',
 '364516',
 '364846',
 '364848',
 '364849',
 '364849',
 '364850',
 '364851',
 '365222',
 '365226',
 '36568',
 '367226',
 '367226',
 '367228',
 '367229',
 '367230',
 '367230',
 '367231',
 '367232',
 '367655',
 '368323',
 '36864',
 '36865',
 '36866',
 '368703',
 '36928',
 '36928',
 '36947',
 '36947',
 '36963',
 '36967',
 '36973',
 '36973',
 '370129',
 '370129',
 '370365',
 '370365',
 '370369',
 '370370',
 '370371',
 '370372',
 '370373',
 '370375',
 '370376',
 '370377',
 '371060',
 '371110',
 '371110',
 '371110',
 '371362',
 '372622',
 '373450',
 '374746',
 '374887',
 '374910',
 '376564',
 '376564',
 '376566',
 '382649',
 '382651',
 '382652',
 '382652',
 '382652',
 '382652',
 '382652',
 '383121',
 '384461',
 '386525',
 '392091',
 '392092',
 '392096',
 '392096',
 '394140',
 '4133',
 '4133',
 '4133',
 '4133',
 '4134',
 '4135',
 '4136',
 '4137',
 '4138',
 '4579',
 '54636',
 '54636',
 '5727',
 '65303',
 '65304',
 '65306',
 '6563',
 '693',
 '695',
 '7267',
 '7534',
 '7534',
 '7540',
 '7545',
 '7546',
 '7552',
 '7553',
 '7598',
 '8471',
 '8475',
 '9234',
 'A./5. 2152',
 'A./5. 3235',
 'A.5. 11206',
 'A.5. 18509',
 'A/4 45380',
 'A/4 48871',
 'A/4 48871',
 'A/4. 20589',
 'A/4. 34244',
 'A/4. 39886',
 'A/5 21171',
 'A/5 21172',
 'A/5 21173',
 'A/5 21174',
 'A/5 2466',
 'A/5 2817',
 'A/5 3536',
 'A/5 3540',
 'A/5 3594',
 'A/5 3902',
 'A/5. 10482',
 'A/5. 13032',
 'A/5. 2151',
 'A/5. 3336',
 'A/5. 3336',
 'A/5. 3337',
 'A/5. 851',
 'A/S 2816',
 'A4. 54510',
 'C 17369',
 'C 4001',
 'C 7075',
 'C 7076',
 'C 7077',
 'C.A. 17248',
 'C.A. 18723',
 'C.A. 2315',
 'C.A. 2315',
 'C.A. 24579',
 'C.A. 24580',
 'C.A. 2673',
 'C.A. 2673',
 'C.A. 29178',
 'C.A. 29395',
 'C.A. 29566',
 'C.A. 31026',
 'C.A. 31921',
 'C.A. 31921',
 'C.A. 31921',
 'C.A. 33111',
 'C.A. 33112',
 'C.A. 33112',
 'C.A. 33595',
 'C.A. 34260',
 'C.A. 34651',
 'C.A. 34651',
 'C.A. 34651',
 'C.A. 37671',
 'C.A. 37671',
 'C.A. 5547',
 'C.A. 6212',
 'C.A./SOTON 34068',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA 2144',
 'CA. 2314',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'CA. 2343',
 'F.C. 12750',
 'F.C.C. 13528',
 'F.C.C. 13529',
 'F.C.C. 13529',
 'F.C.C. 13529',
 'F.C.C. 13531',
 'Fa 265302',
 'LINE',
 'LINE',
 'LINE',
 'LINE',
 'P/PP 3381',
 'P/PP 3381',
 'PC 17318',
 'PC 17473',
 'PC 17474',
 'PC 17475',
 'PC 17476',
 'PC 17477',
 'PC 17477',
 'PC 17482',
 'PC 17483',
 'PC 17485',
 'PC 17485',
 'PC 17558',
 'PC 17558',
 'PC 17569',
 'PC 17569',
 'PC 17572',
 'PC 17572',
 'PC 17572',
 'PC 17582',
 'PC 17582',
 'PC 17582',
 'PC 17585',
 'PC 17590',
 'PC 17592',
 'PC 17593',
 'PC 17593',
 'PC 17595',
 'PC 17596',
 'PC 17597',
 'PC 17599',
 'PC 17600',
 'PC 17601',
 'PC 17603',
 'PC 17604',
 'PC 17604',
 'PC 17605',
 'PC 17608',
 'PC 17608',
 'PC 17609',
 'PC 17610',
 'PC 17611',
 'PC 17611',
 'PC 17612',
 'PC 17754',
 'PC 17755',
 'PC 17755',
 'PC 17755',
 'PC 17756',
 'PC 17757',
 'PC 17757',
 'PC 17757',
 'PC 17757',
 'PC 17758',
 'PC 17758',
 'PC 17759',
 'PC 17760',
 'PC 17760',
 'PC 17760',
 'PC 17761',
 'PC 17761',
 'PP 4348',
 'PP 9549',
 'PP 9549',
 'S.C./A.4. 23567',
 'S.C./PARIS 2079',
 'S.C./PARIS 2079',
 'S.O./P.P. 3',
 'S.O./P.P. 3',
 'S.O./P.P. 751',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.C. 14879',
 'S.O.P. 1166',
 'S.P. 3464',
 'S.W./PP 752',
 'SC 1748',
 'SC/AH 29037',
 'SC/AH 3085',
 'SC/AH Basle 541',
 'SC/PARIS 2131',
 'SC/PARIS 2133',
 'SC/PARIS 2146',
 'SC/PARIS 2149',
 'SC/PARIS 2167',
 'SC/Paris 2123',
 'SC/Paris 2123',
 'SC/Paris 2123',
 'SC/Paris 2163',
 'SCO/W 1585',
 'SO/C 14885',
 'SOTON/O.Q. 3101305',
 'SOTON/O.Q. 3101306',
 'SOTON/O.Q. 3101307',
 'SOTON/O.Q. 3101310',
 'SOTON/O.Q. 3101311',
 'SOTON/O.Q. 3101312',
 'SOTON/O.Q. 392078',
 'SOTON/O.Q. 392087',
 'SOTON/O2 3101272',
 'SOTON/O2 3101287',
 'SOTON/OQ 3101316',
 'SOTON/OQ 3101317',
 'SOTON/OQ 392076',
 'SOTON/OQ 392082',
 'SOTON/OQ 392086',
 'SOTON/OQ 392089',
 'SOTON/OQ 392090',
 'STON/O 2. 3101269',
 'STON/O 2. 3101273',
 'STON/O 2. 3101274',
 'STON/O 2. 3101275',
 'STON/O 2. 3101280',
 'STON/O 2. 3101285',
 'STON/O 2. 3101286',
 'STON/O 2. 3101288',
 'STON/O 2. 3101289',
 'STON/O 2. 3101292',
 'STON/O 2. 3101293',
 'STON/O 2. 3101294',
 'STON/O2. 3101271',
 'STON/O2. 3101279',
 'STON/O2. 3101279',
 'STON/O2. 3101282',
 'STON/O2. 3101283',
 'STON/O2. 3101290',
 'SW/PP 751',
 'W./C. 14258',
 'W./C. 14263',
 'W./C. 6607',
 'W./C. 6607',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6608',
 'W./C. 6609',
 'W.E.P. 5734',
 'W/C 14208',
 'WE/P 5735',
 'WE/P 5735']

In [185]:
df7.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [187]:
# I can iterate the all columns by one by one 
for i in df7.columns:
    print(df7[i])

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int64
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64
0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64
0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object
0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    1
889    0
890    0
Name: SibSp, Length: 891, dtype: int64
0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    2
889    0
890    0
Name: Parch, Length: 891, dtype: int64
0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object
0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64
0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object
0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [190]:
    for i in df7.columns:
        print(df7[[i]])

     PassengerId
0              1
1              2
2              3
3              4
4              5
..           ...
886          887
887          888
888          889
889          890
890          891

[891 rows x 1 columns]
     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]
     Pclass
0         3
1         1
2         3
3         1
4         3
..      ...
886       2
887       1
888       3
889       1
890       3

[891 rows x 1 columns]
                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]
        Sex
0      male
1    female
2    female
3    female
4      male
..      ...
886    male
887  female
888  female
889    male
890    male

[891 rows x 1 columns]
      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]
     SibSp
0        1
1        1
2        0
3        1
4        0
..     ...
886      0
887      0
888      1
889      0
890      0

[891 rows x 1 columns]
     Parch
0        0
1        0
2        0
3        0
4        0
..     ...
886      0
887      0
888      2
889      0
890      0

[891 rows x 1 columns]
               Ticket
0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
..                ...
886            211536
887            112053
888        W./C. 6607
889            111369
890            370376

[891 rows x 1 columns]
        Fare
0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
..       ...
886  13.0000
887  30.0000
888  23.4500
889  30.0000
890   7.7500

[891 rows x 1 columns]
    Cabin
0     NaN
1     C85
2     NaN
3    C123
4     NaN
..    ...
886   NaN
887   B42
888   NaN
889  C148
890   NaN

[891 rows x 1 columns]
    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
886        S
887        S
888        S
889        C
890        Q

[891 rows x 1 columns]

In [193]:
# add the new column with specified data
df7['Itnesh']='Kumar'

In [194]:
df7

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Kumar,Kumar
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Kumar,Kumar
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Kumar,Kumar
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Kumar,Kumar
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Kumar,Kumar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Kumar,Kumar
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Kumar,Kumar
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Kumar,Kumar
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Kumar,Kumar
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Kumar,Kumar

In [198]:
# Import all the data which is already present
df7['Itnehs']=df7['PassengerId']

In [199]:
df7

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,Kumar
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Kumar
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,Kumar
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,Kumar
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,Kumar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887,Kumar
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888,Kumar
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889,Kumar
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890,Kumar
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891,Kumar

In [203]:
# giving the ouput of data present in cabin columns in the list
pd.Categorical(df7['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [204]:
pd.Categorical(df7['Sex'])

['male', 'female', 'female', 'female', 'male', ..., 'male', 'female', 'female', 'male', 'male']
Length: 891
Categories (2, object): ['female', 'male']

In [209]:
# This is also unique way to extact the of series of particular columns
df7['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [210]:
# if we want to extact the data as null value 
df7['Pclass'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Pclass, Length: 891, dtype: bool

In [211]:
df7['Cabin'].isnull()

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [213]:
df7['Cabin'][df7['Cabin'].isnull()==True]

0      NaN
2      NaN
4      NaN
5      NaN
7      NaN
      ...
884    NaN
885    NaN
886    NaN
888    NaN
890    NaN
Name: Cabin, Length: 687, dtype: object

In [214]:
df7['Cabin'][df7['Cabin'].isnull()==False]

1              C85
3             C123
6              E46
10              G6
11            C103
          ...
871            D35
872    B51 B53 B55
879            C50
887            B42
889           C148
Name: Cabin, Length: 204, dtype: object

In [215]:
ser=df7['Cabin'][df7['Cabin'].isnull()==False]

In [216]:
ser.index

Int64Index([  1,   3,   6,  10,  11,  21,  23,  27,  31,  52,
            ...
            849, 853, 857, 862, 867, 871, 872, 879, 887, 889],
           dtype='int64', length=204)

In [218]:
# extract the all not null value data from the data frame
df7.iloc[ser.index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Kumar
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,Kumar
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,7,Kumar
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,11,Kumar
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,12,Kumar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,872,Kumar
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,873,Kumar
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,880,Kumar
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888,Kumar
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890,Kumar

In [219]:
df7.iloc[[1,3,4,5,6]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Kumar
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,Kumar
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,Kumar
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,6,Kumar
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,7,Kumar

In [221]:
# Fatch the cabin having the null value

In [ ]:
Fatch the cabin having the null value

In [222]:
seri=df7['Cabin'][df7['Cabin'].isnull()==True]

In [223]:
seri.index

Int64Index([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,
            ...
            878, 880, 881, 882, 883, 884, 885, 886, 888, 890],
           dtype='int64', length=687)

In [226]:
df7.iloc[seri.index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,Kumar
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,Kumar
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,Kumar
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,6,Kumar
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,8,Kumar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,885,Kumar
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,886,Kumar
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887,Kumar
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889,Kumar
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891,Kumar

In [228]:
#how many cabin has null value ?
len(seri)

687

In [231]:
# so lets find the highest paid person name
df7[df7['Fare']==max(df7['Fare'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,259,Kumar
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,680,Kumar
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,738,Kumar

In [232]:
df7[df7['Fare']==max(df7['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [237]:
# add the new columns and addition of age and passengerID
df7['new_col']=df7['PassengerId']+df7['Age']

In [238]:
df7

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Itnehs,Itnesh,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,Kumar,23.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,Kumar,40.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3,Kumar,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,4,Kumar,39.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,5,Kumar,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,887,Kumar,914.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,888,Kumar,907.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,889,Kumar,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,890,Kumar,916.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,891,Kumar,923.0

In [ ]:
# task link for total price and name order etc
https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv